/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugasmodul2_pemvis;

import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.JOptionPane;
import javax.swing.Icon;

;
/**
 *
 * @author Erlangga Satrya H
 */
public class Tugas extends javax.swing.JFrame {
int jumlah;
Icon sukses = new javax.swing.ImageIcon(getClass().getResource("/img/sukses2.png"));
Icon cancel = new javax.swing.ImageIcon(getClass().getResource("/img/cancel2.png"));
Icon coba = new javax.swing.ImageIcon(getClass().getResource("/img/coba2.png"));
//    
    public Tugas() {
        initComponents();
        jumlah = 0;
        jumlahCash.getDocument().addDocumentListener(new DocumentListener() {
        
        @Override
        public void insertUpdate(DocumentEvent e) {
            updateKembalian();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            updateKembalian();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            updateKembalian();
        }
        
        
    });
    }
    
    

        
    private void updateKembalian() {
    String cashText = jumlahCash.getText();
    int totalHarga = 0; 
    
    
    

    // Mendapatkan total dari hasilTotal
    if (!Total.getText().isEmpty()) {
        totalHarga = Integer.parseInt(Total.getText());
    }

    // Menghitung kembalian
    if (!cashText.isEmpty()) {
        try {
            int cash = Integer.parseInt(cashText);
            int kembalianValue = cash - totalHarga;
            Kembalian.setText(String.valueOf(kembalianValue));
        } catch (NumberFormatException e) {
            Kembalian.setText("0");
        }
    } else {
          Kembalian.setText("0");
     
 }   
}

  
    
    // Fungsi untuk menghitung total
//public void calculateTotal() {
//    int total = priceIceCream + priceTopping;
//    txtTotal
//}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IceCream = new javax.swing.ButtonGroup();
        Topping = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Menu6 = new javax.swing.JRadioButton();
        Menu5 = new javax.swing.JRadioButton();
        Menu4 = new javax.swing.JRadioButton();
        Menu3 = new javax.swing.JRadioButton();
        Menu2 = new javax.swing.JRadioButton();
        Menu1 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel_Menu1 = new javax.swing.JLabel();
        jLabel_Menu2 = new javax.swing.JLabel();
        jLabel_Menu3 = new javax.swing.JLabel();
        jLabel_Menu4 = new javax.swing.JLabel();
        jLabel_Menu5 = new javax.swing.JLabel();
        jLabel_Menu6 = new javax.swing.JLabel();
        Topping1 = new javax.swing.JRadioButton();
        Topping2 = new javax.swing.JRadioButton();
        Topping3 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Angka = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        Total = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jumlahCash = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        Kembalian = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 51));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 102, 51));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IceCream.add(Menu6);
        jPanel2.add(Menu6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, -1, -1));

        IceCream.add(Menu5);
        Menu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu5ActionPerformed(evt);
            }
        });
        jPanel2.add(Menu5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, -1, -1));

        IceCream.add(Menu4);
        Menu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu4ActionPerformed(evt);
            }
        });
        jPanel2.add(Menu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, -1));

        IceCream.add(Menu3);
        jPanel2.add(Menu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, -1, -1));

        IceCream.add(Menu2);
        Menu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu2ActionPerformed(evt);
            }
        });
        jPanel2.add(Menu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        IceCream.add(Menu1);
        Menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu1ActionPerformed(evt);
            }
        });
        jPanel2.add(Menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel2.setText("Menu Ice Cream");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel_Menu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MenuEsKrim1.jpg"))); // NOI18N
        jPanel2.add(jLabel_Menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel_Menu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MenuEsKrim2.jpg"))); // NOI18N
        jPanel2.add(jLabel_Menu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        jLabel_Menu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MenuEsKrim3.jpg"))); // NOI18N
        jPanel2.add(jLabel_Menu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, -1, -1));

        jLabel_Menu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MenuEsKrim4.jpg"))); // NOI18N
        jPanel2.add(jLabel_Menu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        jLabel_Menu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MenuEsKrim5.jpg"))); // NOI18N
        jPanel2.add(jLabel_Menu5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, -1, -1));

        jLabel_Menu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MenuEsKrim6.jpg"))); // NOI18N
        jPanel2.add(jLabel_Menu6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, -1, -1));

        Topping.add(Topping1);
        Topping1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Topping1ActionPerformed(evt);
            }
        });
        jPanel2.add(Topping1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, -1, -1));

        Topping.add(Topping2);
        jPanel2.add(Topping2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 630, -1, -1));

        Topping.add(Topping3);
        Topping3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Topping3ActionPerformed(evt);
            }
        });
        jPanel2.add(Topping3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 630, -1, -1));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel1.setText("Topping");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 610, -1, -1));

        jPanel3.setBackground(new java.awt.Color(249, 249, 249));
        jPanel3.setPreferredSize(new java.awt.Dimension(590, 394));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel15.setText("Jumlah");

        jButton2.setBackground(new java.awt.Color(251, 241, 229));
        jButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(221, 182, 139));
        jButton2.setText("-");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Angka.setBackground(new java.awt.Color(251, 241, 229));
        Angka.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Angka.setForeground(new java.awt.Color(221, 182, 139));
        Angka.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Angka.setText("0");
        Angka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AngkaActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(251, 241, 229));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(221, 182, 139));
        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(251, 241, 229));
        jButton3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(221, 182, 139));
        jButton3.setText("Bayar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 1, 22)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(221, 182, 139));
        jLabel20.setText("|");

        Total.setBackground(new java.awt.Color(251, 241, 229));
        Total.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Total.setForeground(new java.awt.Color(221, 182, 139));
        Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel17.setText("Total");

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel18.setText("Cash");

        jumlahCash.setBackground(new java.awt.Color(251, 241, 229));
        jumlahCash.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jumlahCash.setForeground(new java.awt.Color(221, 182, 139));
        jumlahCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahCashActionPerformed(evt);
            }
        });
        jumlahCash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jumlahCashKeyReleased(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel19.setText("Kembalian");

        Kembalian.setBackground(new java.awt.Color(251, 241, 229));
        Kembalian.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Kembalian.setForeground(new java.awt.Color(221, 182, 139));
        Kembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembalianActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Trebuchet MS", 1, 22)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(221, 182, 139));
        jLabel22.setText("|");

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(59, 59, 59)
                            .addComponent(jButton3))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jButton2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Angka, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton1)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel20)
                            .addGap(12, 12, 12)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel17)
                                .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jumlahCash, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel22))
                                .addComponent(jLabel18))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel19)
                                .addComponent(Kembalian))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(Angka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlahCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(14, 14, 14))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 46, -1, 290));

        jLabel21.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel21.setText("Past Orders");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 520, 370));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("Tripple Walls");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("ChocoLate Island");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, -1));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setText("Black Forest");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, -1, -1));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setText("Cherry Sunday");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 570, -1, -1));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setText("Red Velvet");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 570, -1, -1));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel9.setText("Waffle Ice Cream");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 570, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tKacang.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tBiskuit.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 630, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tCoklat.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 630, -1, -1));

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel12.setText("Kacang");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 720, -1, -1));

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel13.setText("Biskuit");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 720, -1, -1));

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel14.setText("Coklat");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 720, -1, -1));

        jPanel4.setBackground(new java.awt.Color(249, 249, 249));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 103, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 620, 590, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bannerrr 1.png"))); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1360, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu2ActionPerformed

    private void Menu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu5ActionPerformed

    private void Topping1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Topping1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Topping1ActionPerformed

    private void Topping3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Topping3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Topping3ActionPerformed

    private void AngkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AngkaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AngkaActionPerformed

    private void Menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu1ActionPerformed
        // TODO add your handling code here:
//        rbTrippleWalls.addActionListener(e -> {
//            priceIceCream = 15000; // harga tripple walls
//            calculateTotal(); // Memanggil fungsi untuk menghitung total
//        });
    }//GEN-LAST:event_Menu1ActionPerformed

    private void Menu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (jumlah > 0){
            jumlah--;
        }else{
            JOptionPane.showMessageDialog(this,"Pesan tidak boleh kurang dari 0", "INI PERINGATAN",JOptionPane.WARNING_MESSAGE);
        }
        Angka.setText(String.valueOf(jumlah));
            
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jumlah++;
        Angka.setText(String.valueOf(jumlah));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        IceCream.clearSelection();
        Topping.clearSelection();
        Angka.setText("");
        jumlahCash.setText("");
        Total.setText("");
        Kembalian.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int hargaIceCream = 0;
        int hargaTopping = 0;
        int hargaTotal = 0;
        int diskon = 0;
        
        if(Menu1.isSelected()){
            hargaIceCream = jumlah * 15000;
        }else if (Menu2.isSelected()){
            hargaIceCream = jumlah * 21000;
        }else if (Menu3.isSelected()){
            hargaIceCream = jumlah * 12000;
        }else if (Menu4.isSelected()){
            hargaIceCream = jumlah * 11000;
        }else if (Menu5.isSelected()){
            hargaIceCream = jumlah * 19000;
        }else if (Menu6.isSelected()){
            hargaIceCream = jumlah * 31000;
        }else {
            JOptionPane.showMessageDialog(this, "Pilih Menu Ice Cream terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE,coba);
        }
        
        if(Topping1.isSelected()){
            hargaTopping = jumlah * 6000;
        }else if(Topping2.isSelected()){
            hargaTopping = jumlah * 8000;
        }else if(Topping3.isSelected()){
            hargaTopping = jumlah * 9000;
        }else {
            JOptionPane.showMessageDialog(this, "Pilih Topping Ice Cream terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE,cancel);
        }
        
        hargaTotal = hargaIceCream + hargaTopping;
    
        if (hargaTotal >= 100000){
            diskon = hargaTotal * 5/100;
            hargaTotal -= diskon;
            JOptionPane.showMessageDialog(this, "Berhasil Mendapatkan diskon 5000!", "Peringatan", JOptionPane.WARNING_MESSAGE,sukses);
        }
        Total.setText(String.valueOf(hargaTotal));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void KembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KembalianActionPerformed

    private void jumlahCashKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlahCashKeyReleased
        // TODO add your handling code here:
        try{
            int hargaTotal = Integer.parseInt(Total.getText());
            int Cash = Integer.parseInt(jumlahCash.getText());
            
            if (Cash < hargaTotal){
                Kembalian.setText("Uang anda kurang");
            } else{
                int kembalian = Cash - hargaTotal;
                Kembalian.setText(String.valueOf(kembalian));
            }
        }catch (NumberFormatException e) {
            Kembalian.setText("Masukkan angka saja");
        }
            
            
    }//GEN-LAST:event_jumlahCashKeyReleased

    private void TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalActionPerformed

    private void jumlahCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahCashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahCashActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Angka;
    private javax.swing.ButtonGroup IceCream;
    private javax.swing.JTextField Kembalian;
    private javax.swing.JRadioButton Menu1;
    private javax.swing.JRadioButton Menu2;
    private javax.swing.JRadioButton Menu3;
    private javax.swing.JRadioButton Menu4;
    private javax.swing.JRadioButton Menu5;
    private javax.swing.JRadioButton Menu6;
    private javax.swing.ButtonGroup Topping;
    private javax.swing.JRadioButton Topping1;
    private javax.swing.JRadioButton Topping2;
    private javax.swing.JRadioButton Topping3;
    private javax.swing.JTextField Total;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Menu1;
    private javax.swing.JLabel jLabel_Menu2;
    private javax.swing.JLabel jLabel_Menu3;
    private javax.swing.JLabel jLabel_Menu4;
    private javax.swing.JLabel jLabel_Menu5;
    private javax.swing.JLabel jLabel_Menu6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    public javax.swing.JTextField jumlahCash;
    // End of variables declaration//GEN-END:variables
}
