/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class formulirpendaftaran1 extends javax.swing.JFrame {

    /**
     * Creates new form
     */
    public formulirpendaftaran1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jeniskelaminbuttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        labelPendaftaran = new javax.swing.JLabel();
        labelTempat = new javax.swing.JLabel();
        labelAlamat1 = new javax.swing.JLabel();
        labelAlamat2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelNama = new javax.swing.JLabel();
        labelTempatlahir = new javax.swing.JLabel();
        labelTanggallahir = new javax.swing.JLabel();
        labelJeniskelamin = new javax.swing.JLabel();
        labelAlamatformulir = new javax.swing.JLabel();
        labelNotelp = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelMember = new javax.swing.JLabel();
        outputNama = new javax.swing.JTextField();
        outputTempatlahir = new javax.swing.JTextField();
        outputTanggallahir = new javax.swing.JTextField();
        outputAlamat = new javax.swing.JTextField();
        outputNotelp = new javax.swing.JTextField();
        outputEmail = new javax.swing.JTextField();
        buttonSimpan = new javax.swing.JButton();
        outputJeniskelamin = new javax.swing.JTextField();
        outputMember = new javax.swing.JTextField();
        buttonKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        labelPendaftaran.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        labelPendaftaran.setText("Pendaftaran Anggota GYM ");

        labelTempat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelTempat.setText("PLUTONS FITNESS");

        labelAlamat1.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        labelAlamat1.setText("JL. SIWALANPANJI, BUDURAN SIDOARJO, ");

        labelAlamat2.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        labelAlamat2.setText("Siwalan Panji, Kec. Buduran, Kab. Sidoarjo Prov. Jawa Timur");

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\bkkb-01.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPendaftaran, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(labelTempat)
                                .addGap(45, 45, 45))
                            .addComponent(labelAlamat1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(179, 179, 179))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelAlamat2)
                        .addGap(169, 169, 169))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(labelPendaftaran)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTempat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelAlamat1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelAlamat2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 120));

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));
        jPanel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        labelNama.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelNama.setText("Nama :");

        labelTempatlahir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelTempatlahir.setText("Tempat Lahir :");

        labelTanggallahir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelTanggallahir.setText("Tanggal Lahir :");

        labelJeniskelamin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelJeniskelamin.setText("Jenis Kelamin :");

        labelAlamatformulir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelAlamatformulir.setText("Alamat :");

        labelNotelp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelNotelp.setText("No Telp :");

        labelEmail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelEmail.setText("Email :");

        labelMember.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelMember.setText("Member :");

        outputNama.setEditable(false);
        outputNama.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        outputNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputNamaActionPerformed(evt);
            }
        });

        outputTempatlahir.setEditable(false);
        outputTempatlahir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        outputTanggallahir.setEditable(false);
        outputTanggallahir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        outputAlamat.setEditable(false);
        outputAlamat.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        outputNotelp.setEditable(false);
        outputNotelp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        outputEmail.setEditable(false);
        outputEmail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        buttonSimpan.setText("Kembali");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        outputJeniskelamin.setEditable(false);
        outputJeniskelamin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        outputJeniskelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputJeniskelaminActionPerformed(evt);
            }
        });

        outputMember.setEditable(false);
        outputMember.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        buttonKeluar.setText("Keluar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(buttonKeluar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonSimpan))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelNotelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelAlamatformulir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelTempatlahir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelTanggallahir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelJeniskelamin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(outputEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(outputNotelp, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(outputAlamat, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(outputJeniskelamin, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(outputTanggallahir, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(outputTempatlahir, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(outputNama, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(outputMember))))
                .addGap(0, 108, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNama)
                    .addComponent(outputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTempatlahir)
                    .addComponent(outputTempatlahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTanggallahir)
                    .addComponent(outputTanggallahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelJeniskelamin)
                    .addComponent(outputJeniskelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAlamatformulir))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputNotelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNotelp))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail)
                    .addComponent(outputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMember)
                    .addComponent(outputMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSimpan)
                    .addComponent(buttonKeluar))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 590, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void outputNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputNamaActionPerformed

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void outputJeniskelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputJeniskelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputJeniskelaminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulirpendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulirpendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulirpendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulirpendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formulirpendaftaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonKeluar;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.ButtonGroup jeniskelaminbuttonGroup;
    private javax.swing.JLabel labelAlamat1;
    private javax.swing.JLabel labelAlamat2;
    private javax.swing.JLabel labelAlamatformulir;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelJeniskelamin;
    private javax.swing.JLabel labelMember;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelNotelp;
    private javax.swing.JLabel labelPendaftaran;
    private javax.swing.JLabel labelTanggallahir;
    private javax.swing.JLabel labelTempat;
    private javax.swing.JLabel labelTempatlahir;
    public javax.swing.JTextField outputAlamat;
    public javax.swing.JTextField outputEmail;
    public javax.swing.JTextField outputJeniskelamin;
    public javax.swing.JTextField outputMember;
    public javax.swing.JTextField outputNama;
    public javax.swing.JTextField outputNotelp;
    public javax.swing.JTextField outputTanggallahir;
    public javax.swing.JTextField outputTempatlahir;
    // End of variables declaration//GEN-END:variables
}
