
import javax.swing.Icon;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class FrameKatsu extends javax.swing.JFrame {
Icon iconFailed = new javax.swing.ImageIcon(getClass().getResource("failed.png"));
    
    public FrameKatsu() {
        initComponents();

        jumlah.setText("1");
        // menambahkan DocumentListener untuk jumlahCash
        jumlahCash.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateKembalian();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateKembalian();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateKembalian();
            }
        });
    }

    private void updateKembalian() {
        String cashText = jumlahCash.getText();
        int totalHarga = 0; // Pastikan ini diisi dari hasilTotal

        // Mendapatkan total dari hasilTotal
        if (!hasilTotal.getText().isEmpty()) {
            totalHarga = Integer.parseInt(hasilTotal.getText());
        }

        // Menghitung kembalian
        if (!cashText.isEmpty()) {
            try {
                int cash = Integer.parseInt(cashText);
                int kembalianValue = cash - totalHarga;
                kembalian.setText(String.valueOf(kembalianValue));
            } catch (NumberFormatException e) {
                kembalian.setText("0");
            }
        } else {
            kembalian.setText("0");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupjajan = new javax.swing.ButtonGroup();
        buttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        gambar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelAnekajajan = new javax.swing.JLabel();
        OriKatsu = new javax.swing.JRadioButton();
        SpKatsu = new javax.swing.JRadioButton();
        GyuKatsu = new javax.swing.JRadioButton();
        Fillet = new javax.swing.JRadioButton();
        FriedChick = new javax.swing.JRadioButton();
        Gyoza = new javax.swing.JRadioButton();
        labelSauce = new javax.swing.JLabel();
        SoySauce = new javax.swing.JRadioButton();
        Curry = new javax.swing.JRadioButton();
        Nashville = new javax.swing.JRadioButton();
        labelJumlah = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        kurang = new javax.swing.JButton();
        jumlah = new javax.swing.JTextField();
        tambah = new javax.swing.JButton();
        total = new javax.swing.JButton();
        hasilTotal = new javax.swing.JTextField();
        labelCash = new javax.swing.JLabel();
        jumlahCash = new javax.swing.JTextField();
        labelKembali = new javax.swing.JLabel();
        kembalian = new javax.swing.JTextField();
        batalkanPesanan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 102, 0));

        gambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/katsumenu.png"))); // NOI18N
        gambar.setText("sek");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gambar, javax.swing.GroupLayout.PREFERRED_SIZE, 620, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(gambar)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 180));

        jPanel2.setBackground(new java.awt.Color(248, 199, 103));

        labelAnekajajan.setBackground(new java.awt.Color(195, 110, 25));
        labelAnekajajan.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        labelAnekajajan.setForeground(new java.awt.Color(255, 255, 255));
        labelAnekajajan.setText("Pricelist :");
        labelAnekajajan.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));
        labelAnekajajan.setOpaque(true);

        buttonGroupjajan.add(OriKatsu);
        OriKatsu.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        OriKatsu.setForeground(new java.awt.Color(204, 102, 0));
        OriKatsu.setText("Original  Katsu - 15000");
        OriKatsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OriKatsuActionPerformed(evt);
            }
        });

        buttonGroupjajan.add(SpKatsu);
        SpKatsu.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        SpKatsu.setForeground(new java.awt.Color(204, 102, 0));
        SpKatsu.setText("Spicy Katsu - 17000");
        SpKatsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpKatsuActionPerformed(evt);
            }
        });

        buttonGroupjajan.add(GyuKatsu);
        GyuKatsu.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        GyuKatsu.setForeground(new java.awt.Color(204, 102, 0));
        GyuKatsu.setText("GyuKatsu - 25000");

        buttonGroupjajan.add(Fillet);
        Fillet.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        Fillet.setForeground(new java.awt.Color(204, 102, 0));
        Fillet.setText("Chicken Fillet - 12000");
        Fillet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilletActionPerformed(evt);
            }
        });

        buttonGroupjajan.add(FriedChick);
        FriedChick.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        FriedChick.setForeground(new java.awt.Color(204, 102, 0));
        FriedChick.setText("Fried Chicken - 9000");
        FriedChick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FriedChickActionPerformed(evt);
            }
        });

        buttonGroupjajan.add(Gyoza);
        Gyoza.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        Gyoza.setForeground(new java.awt.Color(204, 102, 0));
        Gyoza.setText("Gyoza - 8000");

        labelSauce.setBackground(new java.awt.Color(193, 109, 25));
        labelSauce.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        labelSauce.setForeground(new java.awt.Color(255, 255, 255));
        labelSauce.setText("Sauce :");
        labelSauce.setOpaque(true);

        buttonGroup.add(SoySauce);
        SoySauce.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        SoySauce.setForeground(new java.awt.Color(204, 102, 0));
        SoySauce.setText("Soy Sauce");
        SoySauce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoySauceActionPerformed(evt);
            }
        });

        buttonGroup.add(Curry);
        Curry.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        Curry.setForeground(new java.awt.Color(204, 102, 0));
        Curry.setText("Japanese Curry - 5000");

        buttonGroup.add(Nashville);
        Nashville.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        Nashville.setForeground(new java.awt.Color(204, 102, 0));
        Nashville.setText("Nashville - 5000");
        Nashville.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NashvilleActionPerformed(evt);
            }
        });

        labelJumlah.setBackground(new java.awt.Color(193, 109, 25));
        labelJumlah.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        labelJumlah.setForeground(new java.awt.Color(255, 255, 255));
        labelJumlah.setText("Jumlah :");
        labelJumlah.setOpaque(true);

        labelTotal.setBackground(new java.awt.Color(193, 109, 25));
        labelTotal.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        labelTotal.setForeground(new java.awt.Color(255, 255, 255));
        labelTotal.setText("Total ");
        labelTotal.setOpaque(true);

        kurang.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        kurang.setForeground(new java.awt.Color(204, 102, 0));
        kurang.setText("-");
        kurang.setOpaque(true);
        kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangActionPerformed(evt);
            }
        });

        jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahActionPerformed(evt);
            }
        });

        tambah.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        tambah.setForeground(new java.awt.Color(204, 102, 0));
        tambah.setText("+");
        tambah.setOpaque(true);
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        total.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        total.setForeground(new java.awt.Color(204, 102, 0));
        total.setText("TOTAL :");
        total.setOpaque(true);
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });

        hasilTotal.setEditable(false);

        labelCash.setBackground(new java.awt.Color(193, 109, 25));
        labelCash.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        labelCash.setForeground(new java.awt.Color(255, 255, 255));
        labelCash.setText("cash");
        labelCash.setOpaque(true);

        jumlahCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahCashActionPerformed(evt);
            }
        });

        labelKembali.setBackground(new java.awt.Color(193, 109, 25));
        labelKembali.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        labelKembali.setForeground(new java.awt.Color(255, 255, 255));
        labelKembali.setText("Kembalian");
        labelKembali.setOpaque(true);

        kembalian.setEditable(false);
        kembalian.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        kembalian.setForeground(new java.awt.Color(204, 102, 0));
        kembalian.setOpaque(true);

        batalkanPesanan.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        batalkanPesanan.setForeground(new java.awt.Color(204, 102, 0));
        batalkanPesanan.setText("Batalkan Pesanan");
        batalkanPesanan.setOpaque(true);
        batalkanPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalkanPesananActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(batalkanPesanan)
                    .addComponent(labelSauce, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(total)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hasilTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(123, 123, 123)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCash, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlahCash, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelKembali)
                            .addComponent(kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(OriKatsu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Fillet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SpKatsu)
                                    .addComponent(FriedChick)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(kurang, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                    .addComponent(SoySauce, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(Curry)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nashville)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(GyuKatsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Gyoza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(labelAnekajajan, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labelAnekajajan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OriKatsu)
                    .addComponent(SpKatsu)
                    .addComponent(GyuKatsu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fillet)
                    .addComponent(FriedChick)
                    .addComponent(Gyoza))
                .addGap(18, 18, 18)
                .addComponent(labelSauce, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SoySauce)
                    .addComponent(Curry)
                    .addComponent(Nashville))
                .addGap(18, 18, 18)
                .addComponent(labelJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(kurang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelKembali, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelCash, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hasilTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(batalkanPesanan)
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 620, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
    // Mendapatkan nilai dari text field jumlah
    int currentJumlah;

    // Jika text field jumlah kosong, set currentJumlah ke 0
    if (jumlah.getText().isEmpty()) {
        currentJumlah = 0;
    } else {
        // Mengonversi nilai yang ada di text field menjadi integer
        currentJumlah = Integer.parseInt(jumlah.getText());
    }
    
    // Menambah jumlah pesanan
    currentJumlah++;
    
    // Memperbarui nilai pada text field jumlah
    jumlah.setText(String.valueOf(currentJumlah));
    }//GEN-LAST:event_tambahActionPerformed

    private void kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangActionPerformed
    // Mendapatkan nilai dari text field jumlah
    int currentJumlah = Integer.parseInt(jumlah.getText());

    // Mengurangi jumlah pesanan jika lebih dari 0
    if (currentJumlah > 1) {
        currentJumlah--;
    }
    
    // Memperbarui nilai pada text field jumlah
    jumlah.setText(String.valueOf(currentJumlah));
    }//GEN-LAST:event_kurangActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed

    // Mendapatkan jumlah pesanan dari text field jumlah
    int jumlahPesanan = Integer.parseInt(jumlah.getText());
    
    // Mendefinisikan harga jajanan pasar dan topping
    int totalHarga = 0;
    int diskon = 0;
    int hargaTopping = 0;

    // Mengecek pilihan jajanan pasar
    if (OriKatsu.isSelected()) {
        totalHarga = 15000 * jumlahPesanan; 
    } else if (SpKatsu.isSelected()) {
        totalHarga = 17000 * jumlahPesanan; 
    } else if (GyuKatsu.isSelected()) {
        totalHarga = 25000 * jumlahPesanan; 
    } else if (Fillet.isSelected()) {
        totalHarga = 12000 * jumlahPesanan; 
    } else if (FriedChick.isSelected()) {
        totalHarga = 9000 * jumlahPesanan; 
    } else if (Gyoza.isSelected()) {
        totalHarga = 8000 * jumlahPesanan; 
    } else {
        // Menampilkan pop-up peringatan jika tidak ada jajanan yang dipilih
        JOptionPane.showMessageDialog(null, "Mohon isi Pesanan Terlebih Dahulu!", "Gagal", JOptionPane.INFORMATION_MESSAGE, iconFailed);
        return; // Keluar dari metode jika tidak ada jajanan yang dipilih
    }

    if (Curry.isSelected()) {
        hargaTopping += 5000 * jumlahPesanan;
    } else if(Nashville.isSelected()) {
        hargaTopping += 5000 * jumlahPesanan;
    }

    // Menambahkan harga topping ke total harga
    totalHarga += hargaTopping;

    // Mengecek apakah total harga melebihi Rp. 100.000 untuk diskon
    if (totalHarga > 100000) {
        diskon = totalHarga * 5 / 100; // Menghitung diskon 5%
        totalHarga -= diskon; // Mengurangi total dengan diskon
    }

    // Menampilkan total harga pada text field hasilTotal
    hasilTotal.setText(String.valueOf(totalHarga));
    }//GEN-LAST:event_totalActionPerformed

    private void jumlahCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahCashActionPerformed
    
    }//GEN-LAST:event_jumlahCashActionPerformed

    private void batalkanPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalkanPesananActionPerformed
    buttonGroupjajan.clearSelection();
    buttonGroup.clearSelection();
    jumlah.setText("");
    hasilTotal.setText("");
    jumlahCash.setText("");
    kembalian.setText("");
    }//GEN-LAST:event_batalkanPesananActionPerformed

    private void jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahActionPerformed
        // TODO add your handling code here:
    jumlah.setText("1");
    }//GEN-LAST:event_jumlahActionPerformed

    private void OriKatsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OriKatsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OriKatsuActionPerformed

    private void FilletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilletActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FilletActionPerformed

    private void SpKatsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpKatsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SpKatsuActionPerformed

    private void FriedChickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FriedChickActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FriedChickActionPerformed

    private void SoySauceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoySauceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SoySauceActionPerformed

    private void NashvilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NashvilleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NashvilleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameKatsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameKatsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameKatsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameKatsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameKatsu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Curry;
    private javax.swing.JRadioButton Fillet;
    private javax.swing.JRadioButton FriedChick;
    private javax.swing.JRadioButton Gyoza;
    private javax.swing.JRadioButton GyuKatsu;
    private javax.swing.JRadioButton Nashville;
    private javax.swing.JRadioButton OriKatsu;
    private javax.swing.JRadioButton SoySauce;
    private javax.swing.JRadioButton SpKatsu;
    private javax.swing.JButton batalkanPesanan;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.ButtonGroup buttonGroupjajan;
    private javax.swing.JLabel gambar;
    private javax.swing.JTextField hasilTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField jumlah;
    private javax.swing.JTextField jumlahCash;
    private javax.swing.JTextField kembalian;
    public javax.swing.JButton kurang;
    private javax.swing.JLabel labelAnekajajan;
    private javax.swing.JLabel labelCash;
    private javax.swing.JLabel labelJumlah;
    private javax.swing.JLabel labelKembali;
    private javax.swing.JLabel labelSauce;
    private javax.swing.JLabel labelTotal;
    public javax.swing.JButton tambah;
    private javax.swing.JButton total;
    // End of variables declaration//GEN-END:variables
}
