/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas1;

import java.awt.Font;
import java.io.File;

/**
 *
 * @author Admin
 */
public class form1 extends javax.swing.JFrame {

    public form1() {
        initComponents();
        jLabelOutName.setText(form.namaLengkap);
        jLabelOutEmail.setText(form.Email);
        jLabelOutUmur.setText(form.Umur);
        jLabelOutJenisKelamin.setText(form.jenisKelamin);
        jLabelOutDivisi.setText(form.Divisi);
        jLabelOutAlamat.setText(form.Alamat);
        
        try{
            File fontStyle = new File("src/resources/font/Poppins-Regular.ttf");
            Font font = Font.createFont(Font.TRUETYPE_FONT, fontStyle).deriveFont(52f);
            Font font1 = Font.createFont(Font.TRUETYPE_FONT, fontStyle).deriveFont(24f);
            Font font36 = Font.createFont(Font.TRUETYPE_FONT, fontStyle).deriveFont(36f);
            Font font14 = Font.createFont(Font.TRUETYPE_FONT, fontStyle).deriveFont(14f);
            jLabelTitle.setFont(font);
            jLabelSubTitle.setFont(font1);
            jLabelSubJudulForm.setFont(font1);
            jButtonExit.setFont(font14);
            
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelR = new javax.swing.JPanel();
        jLabelNamaLengkap = new javax.swing.JLabel();
        jLabelAlamat = new javax.swing.JLabel();
        jLabelDivisi = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelUmur = new javax.swing.JLabel();
        jLabelJenisKelamin = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelSubJudulForm = new javax.swing.JLabel();
        jLabelOutName = new javax.swing.JLabel();
        jLabelOutEmail = new javax.swing.JLabel();
        jLabelOutUmur = new javax.swing.JLabel();
        jLabelOutJenisKelamin = new javax.swing.JLabel();
        jLabelOutDivisi = new javax.swing.JLabel();
        jLabelOutAlamat = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();
        panelL = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelSubTitle = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        panelR.setBackground(new java.awt.Color(255, 255, 255));
        panelR.setLayout(null);

        jLabelNamaLengkap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNamaLengkap.setText("Nama Lengkap");
        panelR.add(jLabelNamaLengkap);
        jLabelNamaLengkap.setBounds(100, 110, 102, 27);

        jLabelAlamat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelAlamat.setText("Alamat");
        panelR.add(jLabelAlamat);
        jLabelAlamat.setBounds(100, 310, 50, 30);

        jLabelDivisi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelDivisi.setText("Divisi");
        panelR.add(jLabelDivisi);
        jLabelDivisi.setBounds(100, 270, 32, 30);

        jLabelEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelEmail.setText("Email");
        panelR.add(jLabelEmail);
        jLabelEmail.setBounds(100, 150, 180, 30);

        jLabelUmur.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelUmur.setText("Umur");
        panelR.add(jLabelUmur);
        jLabelUmur.setBounds(100, 190, 35, 30);

        jLabelJenisKelamin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelJenisKelamin.setText("Jenis Kelamin");
        panelR.add(jLabelJenisKelamin);
        jLabelJenisKelamin.setBounds(100, 230, 81, 30);

        jLabelSubJudulForm.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelSubJudulForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSubJudulForm.setText("Formulir Pendaftaran");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(194, Short.MAX_VALUE)
                .addComponent(jLabelSubJudulForm, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSubJudulForm, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelR.add(jPanel1);
        jPanel1.setBounds(0, 0, 680, 50);

        jLabelOutName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelR.add(jLabelOutName);
        jLabelOutName.setBounds(310, 110, 330, 30);

        jLabelOutEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelR.add(jLabelOutEmail);
        jLabelOutEmail.setBounds(310, 150, 330, 30);

        jLabelOutUmur.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelR.add(jLabelOutUmur);
        jLabelOutUmur.setBounds(310, 190, 330, 30);

        jLabelOutJenisKelamin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelR.add(jLabelOutJenisKelamin);
        jLabelOutJenisKelamin.setBounds(310, 230, 330, 30);

        jLabelOutDivisi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelR.add(jLabelOutDivisi);
        jLabelOutDivisi.setBounds(310, 270, 330, 30);

        jLabelOutAlamat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelR.add(jLabelOutAlamat);
        jLabelOutAlamat.setBounds(310, 310, 350, 30);

        jButtonExit.setBackground(new java.awt.Color(0, 0, 0));
        jButtonExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExit.setText("Keluar");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        panelR.add(jButtonExit);
        jButtonExit.setBounds(520, 390, 110, 40);

        getContentPane().add(panelR);
        panelR.setBounds(0, 140, 680, 470);

        panelL.setBackground(new java.awt.Color(0, 51, 51));
        panelL.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/char.png"))); // NOI18N
        panelL.add(jLabel2);
        jLabel2.setBounds(480, 0, 200, 140);

        jLabelSubTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelSubTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSubTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSubTitle.setText("Telah Mengisi Formulir");
        panelL.add(jLabelSubTitle);
        jLabelSubTitle.setBounds(70, 80, 320, 40);

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 0, 52)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Terima Kasih");
        panelL.add(jLabelTitle);
        jLabelTitle.setBounds(10, 20, 432, 68);

        getContentPane().add(panelL);
        panelL.setBounds(0, 0, 680, 140);

        setSize(new java.awt.Dimension(696, 616));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
//        dispose();
    System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAlamat;
    private javax.swing.JLabel jLabelDivisi;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelJenisKelamin;
    private javax.swing.JLabel jLabelNamaLengkap;
    private javax.swing.JLabel jLabelOutAlamat;
    private javax.swing.JLabel jLabelOutDivisi;
    private javax.swing.JLabel jLabelOutEmail;
    private javax.swing.JLabel jLabelOutJenisKelamin;
    private javax.swing.JLabel jLabelOutName;
    private javax.swing.JLabel jLabelOutUmur;
    private javax.swing.JLabel jLabelSubJudulForm;
    private javax.swing.JLabel jLabelSubTitle;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelUmur;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelL;
    private javax.swing.JPanel panelR;
    // End of variables declaration//GEN-END:variables
}
