
import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class jajananpasar extends javax.swing.JFrame {

    
    public jajananpasar() {
        initComponents();
        
        jumlah.setText("1");
        jumlahCash.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateKembalian();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateKembalian();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateKembalian();
            }
        });
    }

    private void updateKembalian() {
        String cashText = jumlahCash.getText();
        int totalHarga = 0; 

        if (!hasilTotal.getText().isEmpty()) {
            totalHarga = Integer.parseInt(hasilTotal.getText());
        }

        if (!cashText.isEmpty()) {
            try {
                int cash = Integer.parseInt(cashText);
                int kembalianValue = cash - totalHarga;
                kembalian.setText(String.valueOf(kembalianValue));
            } catch (NumberFormatException e) {
                kembalian.setText("0");
            }
        } else {
            kembalian.setText("0");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroupjajan = new javax.swing.ButtonGroup();
        buttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        gambar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelAnekajajan = new javax.swing.JLabel();
        lemper = new javax.swing.JRadioButton();
        pastel = new javax.swing.JRadioButton();
        kueLumpur = new javax.swing.JRadioButton();
        risoles = new javax.swing.JRadioButton();
        pukis = new javax.swing.JRadioButton();
        dadarGulung = new javax.swing.JRadioButton();
        nogoSari = new javax.swing.JRadioButton();
        kueLapis = new javax.swing.JRadioButton();
        labelTopping = new javax.swing.JLabel();
        notopping = new javax.swing.JRadioButton();
        saus = new javax.swing.JRadioButton();
        mayo = new javax.swing.JRadioButton();
        labelJumlah = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        kurang = new javax.swing.JButton();
        jumlah = new javax.swing.JTextField();
        tambah = new javax.swing.JButton();
        total = new javax.swing.JButton();
        hasilTotal = new javax.swing.JTextField();
        labelCash = new javax.swing.JLabel();
        jumlahCash = new javax.swing.JTextField();
        labelKembali = new javax.swing.JLabel();
        kembalian = new javax.swing.JTextField();
        batalkanPesanan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 102, 0));

        gambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anekajajananpasarcakdul.png"))); // NOI18N
        gambar.setText("sek");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gambar, javax.swing.GroupLayout.PREFERRED_SIZE, 620, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(gambar)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 180));

        jPanel2.setBackground(new java.awt.Color(248, 199, 103));

        labelAnekajajan.setBackground(new java.awt.Color(195, 110, 25));
        labelAnekajajan.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        labelAnekajajan.setForeground(new java.awt.Color(255, 255, 255));
        labelAnekajajan.setText("Macam-Macam jajanan pasar :");
        labelAnekajajan.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));
        labelAnekajajan.setOpaque(true);

        buttonGroupjajan.add(lemper);
        lemper.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lemper.setForeground(new java.awt.Color(204, 102, 0));
        lemper.setText("Lemper - 3000");

        buttonGroupjajan.add(pastel);
        pastel.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        pastel.setForeground(new java.awt.Color(204, 102, 0));
        pastel.setText("Pastel - 3000");

        buttonGroupjajan.add(kueLumpur);
        kueLumpur.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        kueLumpur.setForeground(new java.awt.Color(204, 102, 0));
        kueLumpur.setText("kue Lumpur -2000");

        buttonGroupjajan.add(risoles);
        risoles.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        risoles.setForeground(new java.awt.Color(204, 102, 0));
        risoles.setText("Risoles -3000");

        buttonGroupjajan.add(pukis);
        pukis.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        pukis.setForeground(new java.awt.Color(204, 102, 0));
        pukis.setText("Pukis -2000");

        buttonGroupjajan.add(dadarGulung);
        dadarGulung.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        dadarGulung.setForeground(new java.awt.Color(204, 102, 0));
        dadarGulung.setText("Dadar Gulung -2000");

        buttonGroupjajan.add(nogoSari);
        nogoSari.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        nogoSari.setForeground(new java.awt.Color(204, 102, 0));
        nogoSari.setText("Nogo Sari -2000");

        buttonGroupjajan.add(kueLapis);
        kueLapis.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        kueLapis.setForeground(new java.awt.Color(204, 102, 0));
        kueLapis.setText("Kue Lapis -2000");

        labelTopping.setBackground(new java.awt.Color(193, 109, 25));
        labelTopping.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        labelTopping.setForeground(new java.awt.Color(255, 255, 255));
        labelTopping.setText("Topping :");
        labelTopping.setOpaque(true);

        buttonGroup.add(notopping);
        notopping.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        notopping.setForeground(new java.awt.Color(204, 102, 0));
        notopping.setText("tanpa toping");

        buttonGroup.add(saus);
        saus.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        saus.setForeground(new java.awt.Color(204, 102, 0));
        saus.setText("Saus pedas -2000");

        buttonGroup.add(mayo);
        mayo.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        mayo.setForeground(new java.awt.Color(204, 102, 0));
        mayo.setText("mayonaise 2000");

        labelJumlah.setBackground(new java.awt.Color(193, 109, 25));
        labelJumlah.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        labelJumlah.setForeground(new java.awt.Color(255, 255, 255));
        labelJumlah.setText("Jumlah :");
        labelJumlah.setOpaque(true);

        labelTotal.setBackground(new java.awt.Color(193, 109, 25));
        labelTotal.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        labelTotal.setForeground(new java.awt.Color(255, 255, 255));
        labelTotal.setText("Total ");
        labelTotal.setOpaque(true);

        kurang.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        kurang.setForeground(new java.awt.Color(204, 102, 0));
        kurang.setText("-");
        kurang.setOpaque(true);
        kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangActionPerformed(evt);
            }
        });

        jumlah.setEditable(false);

        tambah.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        tambah.setForeground(new java.awt.Color(204, 102, 0));
        tambah.setText("+");
        tambah.setOpaque(true);
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        total.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        total.setForeground(new java.awt.Color(204, 102, 0));
        total.setText("TOTAL :");
        total.setOpaque(true);
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });

        hasilTotal.setEditable(false);

        labelCash.setBackground(new java.awt.Color(193, 109, 25));
        labelCash.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        labelCash.setForeground(new java.awt.Color(255, 255, 255));
        labelCash.setText("cash");
        labelCash.setOpaque(true);

        jumlahCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahCashActionPerformed(evt);
            }
        });

        labelKembali.setBackground(new java.awt.Color(193, 109, 25));
        labelKembali.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        labelKembali.setForeground(new java.awt.Color(255, 255, 255));
        labelKembali.setText("Kembalian");
        labelKembali.setOpaque(true);

        kembalian.setEditable(false);
        kembalian.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        kembalian.setForeground(new java.awt.Color(204, 102, 0));
        kembalian.setOpaque(true);

        batalkanPesanan.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        batalkanPesanan.setForeground(new java.awt.Color(204, 102, 0));
        batalkanPesanan.setText("Batalkan Pesanan");
        batalkanPesanan.setOpaque(true);
        batalkanPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalkanPesananActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(batalkanPesanan)
                    .addComponent(labelAnekajajan, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTopping, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lemper, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pukis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pastel)
                                    .addComponent(dadarGulung))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(kueLumpur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nogoSari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(risoles, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kueLapis)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(saus)
                                .addGap(51, 51, 51)
                                .addComponent(mayo))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(total)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hasilTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(123, 123, 123)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCash, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlahCash, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelKembali)
                            .addComponent(kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(kurang, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addComponent(notopping, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labelAnekajajan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lemper)
                    .addComponent(pastel)
                    .addComponent(kueLumpur)
                    .addComponent(risoles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pukis)
                    .addComponent(dadarGulung)
                    .addComponent(nogoSari)
                    .addComponent(kueLapis))
                .addGap(18, 18, 18)
                .addComponent(labelTopping, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(notopping)
                    .addComponent(saus)
                    .addComponent(mayo))
                .addGap(18, 18, 18)
                .addComponent(labelJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(kurang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelKembali, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelCash, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hasilTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(batalkanPesanan)
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 620, 460));

        pack();
    }// </editor-fold>                        

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {                                       
    // Mendapatkan nilai dari text field jumlah
    int currentJumlah;

    if (jumlah.getText().isEmpty()) {
        currentJumlah = 0;
    } else {
        currentJumlah = Integer.parseInt(jumlah.getText());
    }
    
    currentJumlah++;
    
    jumlah.setText(String.valueOf(currentJumlah));
    }                                      

    private void kurangActionPerformed(java.awt.event.ActionEvent evt) {                                       
    int currentJumlah = Integer.parseInt(jumlah.getText());

    if (currentJumlah > 1) {
        currentJumlah--;
    }
    jumlah.setText(String.valueOf(currentJumlah));
    }                                      

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {                                      
    int jumlahPesanan = Integer.parseInt(jumlah.getText());
    
    int totalHarga = 0;
    int diskon = 0;
    int hargaTopping = 0;

    if (lemper.isSelected()) {
        totalHarga = 3000 * jumlahPesanan; 
    } else if (pastel.isSelected()) {
        totalHarga = 3000 * jumlahPesanan; 
    } else if (kueLumpur.isSelected()) {
        totalHarga = 2000 * jumlahPesanan; 
    } else if (risoles.isSelected()) {
        totalHarga = 3000 * jumlahPesanan; 
    } else if (pukis.isSelected()) {
        totalHarga = 2000 * jumlahPesanan; 
    } else if (dadarGulung.isSelected()) {
        totalHarga = 2000 * jumlahPesanan; 
    } else if (nogoSari.isSelected()) {
        totalHarga = 2000 * jumlahPesanan; 
    } else if (kueLapis.isSelected()) {
        totalHarga = 2000 * jumlahPesanan; 
    } else {
        JOptionPane.showMessageDialog(this, "Mohon pilih salah satu menu terlebih dahulu!");
        return; 
    }

    if (saus.isSelected()) {
        hargaTopping += 2000 * jumlahPesanan; // Harga coklat
    } else if(mayo.isSelected()) {
        hargaTopping += 2000 * jumlahPesanan; // Harga susu
    }

    totalHarga += hargaTopping;

    if (totalHarga > 100000) {
        diskon = totalHarga * 5 / 100; 
        totalHarga -= diskon; 
    }

    hasilTotal.setText(String.valueOf(totalHarga));
    }                                     

    private void jumlahCashActionPerformed(java.awt.event.ActionEvent evt) {                                           
    
    }                                          

    private void batalkanPesananActionPerformed(java.awt.event.ActionEvent evt) {                                                
    buttonGroupjajan.clearSelection();
    buttonGroup.clearSelection();
    jumlah.setText("");
    hasilTotal.setText("");
    jumlahCash.setText("");
    kembalian.setText("");
    }                                               

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jajananpasar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jajananpasar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jajananpasar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jajananpasar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jajananpasar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton batalkanPesanan;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.ButtonGroup buttonGroupjajan;
    private javax.swing.JRadioButton dadarGulung;
    private javax.swing.JLabel gambar;
    private javax.swing.JTextField hasilTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField jumlah;
    private javax.swing.JTextField jumlahCash;
    private javax.swing.JTextField kembalian;
    private javax.swing.JRadioButton kueLapis;
    private javax.swing.JRadioButton kueLumpur;
    public javax.swing.JButton kurang;
    private javax.swing.JLabel labelAnekajajan;
    private javax.swing.JLabel labelCash;
    private javax.swing.JLabel labelJumlah;
    private javax.swing.JLabel labelKembali;
    private javax.swing.JLabel labelTopping;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JRadioButton lemper;
    private javax.swing.JRadioButton mayo;
    private javax.swing.JRadioButton nogoSari;
    private javax.swing.JRadioButton notopping;
    private javax.swing.JRadioButton pastel;
    private javax.swing.JRadioButton pukis;
    private javax.swing.JRadioButton risoles;
    private javax.swing.JRadioButton saus;
    public javax.swing.JButton tambah;
    private javax.swing.JButton total;
    // End of variables declaration                   
}
