/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas1;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Ivan Aditama
 */
public class Modul1 extends javax.swing.JFrame {

    /**
     * Creates new form Modul1
     */
    public Modul1() {
        initComponents();
    }

    private void kosong(){
        txtNama.setText("");
        txtTempat.setText("");
        txtTanggal.setText("");
        txtAlamat.setText("");
        txtNo.setText("");
        txtEmail.setText("");
        txtProdi.setText("");
        btn1.clearSelection();
        cbFakultas.setSelectedIndex(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblNama = new javax.swing.JLabel();
        lblTempat = new javax.swing.JLabel();
        lblTanggal = new javax.swing.JLabel();
        lblJenis = new javax.swing.JLabel();
        lblAlamat = new javax.swing.JLabel();
        lblNo = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblProdi = new javax.swing.JLabel();
        lblFakultas = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtTempat = new javax.swing.JTextField();
        txtTanggal = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        rbLaki = new javax.swing.JRadioButton();
        rbPerempuan = new javax.swing.JRadioButton();
        txtNo = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtProdi = new javax.swing.JTextField();
        cbFakultas = new javax.swing.JComboBox<>();
        cbData = new java.awt.Checkbox();
        btnBatal = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        lblCb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setText("FORMULIR PENDAFTARAN MAHASISWA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 370, 20));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setText("UNIVERSITAS TRUNOJOYO MADURA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel3.setText("Jl. Raya Telang, PO. Box. 2 Kamal, Bangkalan - Madura");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel4.setText("Telp : (031) 3011146, Fax. (031) 3011506");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas1/image44.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 690, 152));

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNama.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNama.setForeground(new java.awt.Color(255, 255, 255));
        lblNama.setText("Nama :");
        jPanel3.add(lblNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        lblTempat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTempat.setForeground(new java.awt.Color(255, 255, 255));
        lblTempat.setText("Tempat Lahir :");
        jPanel3.add(lblTempat, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        lblTanggal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTanggal.setForeground(new java.awt.Color(255, 255, 255));
        lblTanggal.setText("Tanggal Lahir :");
        jPanel3.add(lblTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        lblJenis.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblJenis.setForeground(new java.awt.Color(255, 255, 255));
        lblJenis.setText("Jenis Kelamin :");
        jPanel3.add(lblJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        lblAlamat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAlamat.setForeground(new java.awt.Color(255, 255, 255));
        lblAlamat.setText("Alamat :");
        jPanel3.add(lblAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        lblNo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNo.setForeground(new java.awt.Color(255, 255, 255));
        lblNo.setText("No. Telp :");
        jPanel3.add(lblNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        lblEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email :");
        jPanel3.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        lblProdi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblProdi.setForeground(new java.awt.Color(255, 255, 255));
        lblProdi.setText("Prodi :");
        jPanel3.add(lblProdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        lblFakultas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblFakultas.setForeground(new java.awt.Color(255, 255, 255));
        lblFakultas.setText("Fakultas :");
        jPanel3.add(lblFakultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        jPanel3.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 310, -1));
        jPanel3.add(txtTempat, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 310, -1));
        jPanel3.add(txtTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 310, -1));
        jPanel3.add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 310, -1));

        btn1.add(rbLaki);
        rbLaki.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbLaki.setForeground(new java.awt.Color(255, 255, 255));
        rbLaki.setText("Laki Laki");
        rbLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLakiActionPerformed(evt);
            }
        });
        jPanel3.add(rbLaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        btn1.add(rbPerempuan);
        rbPerempuan.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbPerempuan.setForeground(new java.awt.Color(255, 255, 255));
        rbPerempuan.setText("Perempuan");
        jPanel3.add(rbPerempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));
        jPanel3.add(txtNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 310, -1));
        jPanel3.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 310, -1));
        jPanel3.add(txtProdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 310, -1));

        cbFakultas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fakultas Teknik", "Fakultas Ilmu Pendidikan", "Fakultas Hukum", "Fakultas Pertanian", "Fakultas Keislaman" }));
        jPanel3.add(cbFakultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 310, -1));

        cbData.setForeground(new java.awt.Color(255, 255, 255));
        cbData.setLabel("Data Yang Saya Masukkan Sudah Benar.");
        cbData.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbDataPropertyChange(evt);
            }
        });
        jPanel3.add(cbData, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 400, -1));

        btnBatal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        jPanel3.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, -1));

        btnReset.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel3.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, -1, -1));

        btnSimpan.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel3.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, -1, -1));

        lblCb.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCb.setForeground(new java.awt.Color(255, 51, 51));
        jPanel3.add(lblCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 240, 10));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 120, 700, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void rbLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbLakiActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        kosong();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        page2 p2 = new page2();
        if(cbData.getState()){
            
            p2.txtNama2.setText(txtNama.getText());
            p2.txtTempat2.setText(txtTempat.getText());
            p2.txtTanggal2.setText(txtTanggal.getText());
            if(rbLaki.isSelected()){
                p2.txtJenis2.setText("Laki Laki");
            }else {
                p2.txtJenis2.setText("Perempuan");
            }
            p2.txtAlamat2.setText(txtAlamat.getText());
            p2.txtNo2.setText(txtNo.getText());
            p2.txtEmail2.setText(txtEmail.getText());
            p2.txtProdi2.setText(txtProdi.getText());
            String fakultas = (String)cbFakultas.getSelectedItem().toString();
            p2.txtFakultas2.setText(fakultas);
            
            
        }else{
            lblCb.setText("Mohon centang terlebih dahulu");
        }
        
        if(txtNama.getText().isEmpty()||
           txtTempat.getText().isEmpty()||
           txtTanggal.getText().isEmpty()||
           txtAlamat.getText().isEmpty()||
           txtNo.getText().isEmpty()||
           txtEmail.getText().isEmpty()||
           txtProdi.getText().isEmpty()
           ){
            JOptionPane.showMessageDialog(null, "Form tidak boleh kosong!!", "Peringatan", JOptionPane.ERROR_MESSAGE);
            p2.setVisible(false);
        }else{
            p2.setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void cbDataPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbDataPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDataPropertyChange

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modul1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modul1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modul1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modul1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modul1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btn1;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private java.awt.Checkbox cbData;
    private javax.swing.JComboBox<String> cbFakultas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAlamat;
    private javax.swing.JLabel lblCb;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFakultas;
    private javax.swing.JLabel lblJenis;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNo;
    private javax.swing.JLabel lblProdi;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JLabel lblTempat;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNo;
    private javax.swing.JTextField txtProdi;
    private javax.swing.JTextField txtTanggal;
    private javax.swing.JTextField txtTempat;
    // End of variables declaration//GEN-END:variables
}
