/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nitip;

import javax.swing.JOptionPane;

/**
 *
 * @author shahaflanjaya
 */
public class Frame1 extends javax.swing.JFrame {

    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        RIGHT = new javax.swing.JPanel();
        jLabel2Nama = new javax.swing.JLabel();
        jLabel3Alamat = new javax.swing.JLabel();
        jLabel4Tempat = new javax.swing.JLabel();
        jLabel5Tanggal = new javax.swing.JLabel();
        jLabel6JenisKelamin = new javax.swing.JLabel();
        jLabel7Email = new javax.swing.JLabel();
        jLabel8No = new javax.swing.JLabel();
        jLabel9Fakultas = new javax.swing.JLabel();
        cbSyarat = new javax.swing.JCheckBox();
        jButton1Batal = new javax.swing.JButton();
        jButton2Reset = new javax.swing.JButton();
        jButton3Kirim = new javax.swing.JButton();
        Alamat = new javax.swing.JTextField();
        Tanggal = new javax.swing.JTextField();
        Laki = new javax.swing.JRadioButton();
        Perempuan = new javax.swing.JRadioButton();
        Email = new javax.swing.JTextField();
        No = new javax.swing.JTextField();
        F = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        Prodi = new javax.swing.JTextField();
        SyaratNama = new javax.swing.JLabel();
        SyaratAlamat = new javax.swing.JLabel();
        SyaratTempat = new javax.swing.JLabel();
        SyaratTanggal = new javax.swing.JLabel();
        SyaratEmail = new javax.swing.JLabel();
        SyaratNo = new javax.swing.JLabel();
        SyaratProdi = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        Tempat = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        RIGHT.setBackground(new java.awt.Color(51, 0, 255));

        jLabel2Nama.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2Nama.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2Nama.setText("Nama :");

        jLabel3Alamat.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3Alamat.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3Alamat.setText("Alamat :");

        jLabel4Tempat.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4Tempat.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4Tempat.setText("Tempat Lahir :");

        jLabel5Tanggal.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5Tanggal.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5Tanggal.setText("Tanggal Lahir :");

        jLabel6JenisKelamin.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6JenisKelamin.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6JenisKelamin.setText("Jenis Kelamin :");

        jLabel7Email.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7Email.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7Email.setText("Email :");

        jLabel8No.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel8No.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8No.setText("No Telp :");

        jLabel9Fakultas.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel9Fakultas.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9Fakultas.setText("Fakultas :");

        cbSyarat.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        cbSyarat.setForeground(new java.awt.Color(255, 255, 255));
        cbSyarat.setText("Saya Sudah Mengisi Formulir Dengan Benar");

        jButton1Batal.setText("Batal");
        jButton1Batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1BatalActionPerformed(evt);
            }
        });

        jButton2Reset.setText("Reset");
        jButton2Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ResetActionPerformed(evt);
            }
        });

        jButton3Kirim.setText("Kirim");
        jButton3Kirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3KirimActionPerformed(evt);
            }
        });

        buttonGroup1.add(Laki);
        Laki.setForeground(new java.awt.Color(255, 255, 255));
        Laki.setText("Laki - Laki");

        buttonGroup1.add(Perempuan);
        Perempuan.setForeground(new java.awt.Color(255, 255, 255));
        Perempuan.setText("Perempuan");

        F.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Chose--", "Fakultas Teknik", "Fakultas Pertanian", "Fakultas Kehutanan", "Fakultas Hukum", "Fakultas Kedokteran", " " }));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Prodi :");

        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RIGHTLayout = new javax.swing.GroupLayout(RIGHT);
        RIGHT.setLayout(RIGHTLayout);
        RIGHTLayout.setHorizontalGroup(
            RIGHTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RIGHTLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(RIGHTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RIGHTLayout.createSequentialGroup()
                        .addComponent(jLabel6JenisKelamin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Laki, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Perempuan)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(RIGHTLayout.createSequentialGroup()
                        .addGroup(RIGHTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RIGHTLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(RIGHTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5Tanggal)
                                    .addGroup(RIGHTLayout.createSequentialGroup()
                                        .addGroup(RIGHTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4Tempat))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(RIGHTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(SyaratTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Alamat, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                                            .addComponent(SyaratTempat, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Tanggal)
                                            .addComponent(SyaratNama, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(SyaratAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Nama)
                                            .addComponent(Tempat)))))
                            .addGroup(RIGHTLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(RIGHTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbSyarat)
                                    .addGroup(RIGHTLayout.createSequentialGroup()
                                        .addGroup(RIGHTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7Email)
                                            .addComponent(jLabel8No)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel9Fakultas))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(RIGHTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(No, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Prodi, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(SyaratEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(SyaratNo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(RIGHTLayout.createSequentialGroup()
                                                .addComponent(F, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(SyaratProdi, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RIGHTLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jButton1Batal)
                .addGap(81, 81, 81)
                .addComponent(jButton2Reset)
                .addGap(71, 71, 71)
                .addComponent(jButton3Kirim)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RIGHTLayout.setVerticalGroup(
            RIGHTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RIGHTLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(RIGHTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SyaratNama, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RIGHTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Alamat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SyaratAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RIGHTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4Tempat)
                    .addComponent(Tempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SyaratTempat, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RIGHTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5Tanggal))
                .addGap(1, 1, 1)
                .addComponent(SyaratTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(RIGHTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6JenisKelamin)
                    .addComponent(Laki)
                    .addComponent(Perempuan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RIGHTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7Email)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SyaratEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RIGHTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(No, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8No))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SyaratNo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RIGHTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Prodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(RIGHTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SyaratProdi, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RIGHTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9Fakultas)))
                .addGap(29, 29, 29)
                .addComponent(cbSyarat)
                .addGap(56, 56, 56)
                .addGroup(RIGHTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3Kirim)
                    .addComponent(jButton2Reset)
                    .addComponent(jButton1Batal))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        getContentPane().add(RIGHT);
        RIGHT.setBounds(140, 118, 480, 580);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PENDAFTARAN MAHASISWA");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("UNIVERSITAS TRUNOJOYO MADURA");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("J.Raya Telang Indah,Kamal,Bangkalan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 103, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(94, 94, 94))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(122, 122, 122))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(102, 102, 102))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(140, 0, 480, 120);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1BatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1BatalActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1BatalActionPerformed

    private void jButton2ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ResetActionPerformed
        // TODO add your handling code here:
        Nama.setText("");
        Alamat.setText("");
        Email.setText("");
        No.setText("");
        Tanggal.setText("");
        Tempat.setText("");
        Prodi.setText("");
        F.setSelectedIndex(0);//untuk menghapus index yang dipilih
        buttonGroup1.clearSelection();//menghapus pilihan dari sekumpulan radio button
    }//GEN-LAST:event_jButton2ResetActionPerformed

    private void jButton3KirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3KirimActionPerformed
        // TODO add your handling code here:
       if(cbSyarat.isSelected()){
            Frame2 Frame2 = new Frame2();
            Frame2.Nama.setText(Nama.getText());
            Frame2.Tempat.setText(Tempat.getText());
            Frame2.Tanggal.setText(Tanggal.getText());
            Frame2.No.setText(No.getText());
            Frame2.Email.setText(Email.getText());
            Frame2.Prodi.setText(Prodi.getText());
            Frame2.Alamat.setText(Alamat.getText());
            String Fakultas = (String)F.getSelectedItem().toString();
            Frame2.Fakultas.setText(Fakultas);
            if (Laki.isSelected()){
                Frame2.Kelamin.setText("Laki-Laki");
            } else if (Perempuan.isSelected()){
                Frame2.Kelamin.setText("Perempuan");
            }
            Frame2.setVisible(true);    
            this.dispose();
        }else {
            JOptionPane.showMessageDialog(null,"Harap Checklist Terlebih Dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        
        if(Nama.getText().trim().isEmpty()||
           Tempat.getText().trim().isEmpty()||
           Tanggal.getText().trim().isEmpty()||
           Alamat.getText().trim().isEmpty()||
           No.getText().trim().isEmpty()||
           Email.getText().trim().isEmpty()||
           Prodi.getText().trim().isEmpty()
                ){
            SyaratNama.setText("Form harus diisi!!!");
            SyaratTempat.setText("Form harus diisi!!!");
            SyaratTanggal.setText("Form harus diisi!!!");
            SyaratAlamat.setText("Form harus diisi!!!");
            SyaratNo.setText("Form harus diisi!!!");
            SyaratEmail.setText("Form harus diisi!!!");
            SyaratProdi.setText("Form harus diisi!!!");
            
        }else{
            SyaratNama.setText(null);
            SyaratTempat.setText(null);
            SyaratTanggal.setText(null);
            SyaratAlamat.setText(null);
            SyaratNo.setText(null);
            SyaratEmail.setText(null);
            SyaratProdi.setText(null);
        }
    }//GEN-LAST:event_jButton3KirimActionPerformed
}
    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alamat;
    private javax.swing.JTextField Email;
    private javax.swing.JComboBox<String> F;
    private javax.swing.JRadioButton Laki;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField No;
    private javax.swing.JRadioButton Perempuan;
    private javax.swing.JTextField Prodi;
    private javax.swing.JPanel RIGHT;
    private javax.swing.JLabel SyaratAlamat;
    private javax.swing.JLabel SyaratEmail;
    private javax.swing.JLabel SyaratNama;
    private javax.swing.JLabel SyaratNo;
    private javax.swing.JLabel SyaratProdi;
    private javax.swing.JLabel SyaratTanggal;
    private javax.swing.JLabel SyaratTempat;
    private javax.swing.JTextField Tanggal;
    private javax.swing.JTextField Tempat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbSyarat;
    private javax.swing.JButton jButton1Batal;
    private javax.swing.JButton jButton2Reset;
    private javax.swing.JButton jButton3Kirim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2Nama;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel3Alamat;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel4Tempat;
    private javax.swing.JLabel jLabel5Tanggal;
    private javax.swing.JLabel jLabel6JenisKelamin;
    private javax.swing.JLabel jLabel7Email;
    private javax.swing.JLabel jLabel8No;
    private javax.swing.JLabel jLabel9Fakultas;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
