/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modul2;

import javax.swing.JOptionPane;
import javax.swing.Icon;

/**
 *
 * @author HP VICTUS
 */
public class frame2 extends javax.swing.JFrame {
    int jumlah = 0;
    Icon icon = new javax.swing.ImageIcon(getClass().getResource("/modul2/Letter-X-icon_34793.png"));

    
    /**
     * Creates new form frame2
     */
    public frame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.ButtonGroup();
        Topping = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Rb1 = new javax.swing.JRadioButton();
        Rb2 = new javax.swing.JRadioButton();
        Rb3 = new javax.swing.JRadioButton();
        Rb4 = new javax.swing.JRadioButton();
        Rb5 = new javax.swing.JRadioButton();
        Rb6 = new javax.swing.JRadioButton();
        Rb7 = new javax.swing.JRadioButton();
        Rb8 = new javax.swing.JRadioButton();
        Rb9 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        Rbt1 = new javax.swing.JRadioButton();
        Rbt3 = new javax.swing.JRadioButton();
        Rbt5 = new javax.swing.JRadioButton();
        Rbt2 = new javax.swing.JRadioButton();
        Rbt4 = new javax.swing.JRadioButton();
        Rbt6 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        kurang = new javax.swing.JButton();
        Angka = new javax.swing.JTextField();
        Tambah = new javax.swing.JButton();
        Hitung = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        Total = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Cash = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        JSusok = new javax.swing.JTextField();
        Reset = new javax.swing.JButton();
        Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 51, 0));

        jLabel1.setFont(new java.awt.Font("BankGothic Md BT", 1, 24)); // NOI18N
        jLabel1.setText("PIZZA SULTAN BOSSS");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP VICTUS\\Downloads\\Untitled design (2).png")); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP VICTUS\\Downloads\\Untitled design (4).png")); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel4.setFont(new java.awt.Font("BankGothic Md BT", 1, 24)); // NOI18N
        jLabel4.setText("MENYEDIAKAN SEGALA JENIS PIZZA");

        jLabel5.setFont(new java.awt.Font("BankGothic Md BT", 1, 24)); // NOI18N
        jLabel5.setText("TIDAK MENERIMA PEMESANAN");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Telp. 0000-00000");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(32, 32, 32))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(109, 109, 109))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 915, 150);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Garamond", 1, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("P");

        jLabel16.setFont(new java.awt.Font("Garamond", 1, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("I");

        jLabel17.setFont(new java.awt.Font("Garamond", 1, 48)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Z");

        jLabel18.setFont(new java.awt.Font("Garamond", 1, 48)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Z");

        jLabel19.setFont(new java.awt.Font("Garamond", 1, 48)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("A");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addContainerGap(310, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 128, 134, 770);

        jLabel7.setFont(new java.awt.Font("Century751 No2 BT", 1, 18)); // NOI18N
        jLabel7.setText("Menu Pizza :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(146, 162, 142, 23);

        Menu.add(Rb1);
        Rb1.setFont(new java.awt.Font("Century751 SeBd BT", 0, 14)); // NOI18N
        Rb1.setText("California Pizza - Rp.50.000");
        jPanel1.add(Rb1);
        Rb1.setBounds(146, 191, 205, 23);

        Menu.add(Rb2);
        Rb2.setFont(new java.awt.Font("Century751 SeBd BT", 0, 14)); // NOI18N
        Rb2.setText(" Pizza Neapolitan - Rp.150.000");
        jPanel1.add(Rb2);
        Rb2.setBounds(146, 226, 223, 23);

        Menu.add(Rb3);
        Rb3.setFont(new java.awt.Font("Century751 SeBd BT", 0, 14)); // NOI18N
        Rb3.setText("Pizza Sicilia - Rp. 200.000");
        jPanel1.add(Rb3);
        Rb3.setBounds(146, 261, 213, 23);

        Menu.add(Rb4);
        Rb4.setFont(new java.awt.Font("Century751 SeBd BT", 0, 14)); // NOI18N
        Rb4.setText("Pizza Margherita - Rp.250.000");
        jPanel1.add(Rb4);
        Rb4.setBounds(398, 191, 247, 23);

        Menu.add(Rb5);
        Rb5.setFont(new java.awt.Font("Century751 SeBd BT", 0, 14)); // NOI18N
        Rb5.setText("Pizza Marinara - Rp. 300.000");
        jPanel1.add(Rb5);
        Rb5.setBounds(398, 226, 226, 23);

        Menu.add(Rb6);
        Rb6.setFont(new java.awt.Font("Century751 SeBd BT", 0, 14)); // NOI18N
        Rb6.setText("Chicago Pizza - Rp.350.000");
        jPanel1.add(Rb6);
        Rb6.setBounds(400, 260, 226, 23);

        Menu.add(Rb7);
        Rb7.setFont(new java.awt.Font("Century751 SeBd BT", 0, 14)); // NOI18N
        Rb7.setText("Pizza Romana - Rp.400.000");
        jPanel1.add(Rb7);
        Rb7.setBounds(663, 191, 203, 23);

        Menu.add(Rb8);
        Rb8.setFont(new java.awt.Font("Century751 SeBd BT", 0, 14)); // NOI18N
        Rb8.setText("Pizza calzone Rp.450.000");
        jPanel1.add(Rb8);
        Rb8.setBounds(663, 226, 203, 23);

        Menu.add(Rb9);
        Rb9.setFont(new java.awt.Font("Century751 SeBd BT", 0, 14)); // NOI18N
        Rb9.setText("Pizza frita - Rp.500.000");
        jPanel1.add(Rb9);
        Rb9.setBounds(663, 261, 203, 23);

        jLabel8.setFont(new java.awt.Font("Century751 No2 BT", 1, 18)); // NOI18N
        jLabel8.setText("Topping :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(146, 328, 85, 23);

        Topping.add(Rbt1);
        Rbt1.setFont(new java.awt.Font("Century751 SeBd BT", 0, 14)); // NOI18N
        Rbt1.setText("Keju Mozarella - Rp.50.000");
        jPanel1.add(Rbt1);
        Rbt1.setBounds(146, 363, 213, 23);

        Topping.add(Rbt3);
        Rbt3.setFont(new java.awt.Font("Century751 SeBd BT", 0, 14)); // NOI18N
        Rbt3.setText("Pepproni - Rp.60.000");
        jPanel1.add(Rbt3);
        Rbt3.setBounds(398, 363, 161, 23);

        Topping.add(Rbt5);
        Rbt5.setFont(new java.awt.Font("Century751 SeBd BT", 0, 14)); // NOI18N
        Rbt5.setText("Jamur Tiram - Rp.35.000");
        jPanel1.add(Rbt5);
        Rbt5.setBounds(663, 363, 188, 23);

        Topping.add(Rbt2);
        Rbt2.setFont(new java.awt.Font("Century751 SeBd BT", 0, 14)); // NOI18N
        Rbt2.setText("Sosis - Rp.40.000");
        jPanel1.add(Rbt2);
        Rbt2.setBounds(146, 404, 213, 23);

        Topping.add(Rbt4);
        Rbt4.setFont(new java.awt.Font("Century751 SeBd BT", 0, 14)); // NOI18N
        Rbt4.setText("Daging Ayam - Rp.80.000");
        jPanel1.add(Rbt4);
        Rbt4.setBounds(398, 404, 187, 23);

        Topping.add(Rbt6);
        Rbt6.setFont(new java.awt.Font("Century751 SeBd BT", 0, 14)); // NOI18N
        Rbt6.setText("Daging B2 - Rp.200.000");
        jPanel1.add(Rbt6);
        Rbt6.setBounds(663, 404, 188, 23);

        jLabel9.setText("------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(150, 445, 778, 16);

        jLabel10.setFont(new java.awt.Font("Century751 SeBd BT", 1, 18)); // NOI18N
        jLabel10.setText("Jumlah : ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(146, 467, 100, 23);

        kurang.setText("-");
        kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangActionPerformed(evt);
            }
        });
        jPanel1.add(kurang);
        kurang.setBounds(146, 496, 33, 30);

        Angka.setEditable(false);
        Angka.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Angka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AngkaActionPerformed(evt);
            }
        });
        jPanel1.add(Angka);
        Angka.setBounds(191, 496, 50, 30);

        Tambah.setText("+");
        Tambah.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                TambahInputMethodTextChanged(evt);
            }
        });
        Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahActionPerformed(evt);
            }
        });
        jPanel1.add(Tambah);
        Tambah.setBounds(253, 496, 36, 30);

        Hitung.setText("Hitung");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });
        jPanel1.add(Hitung);
        Hitung.setBounds(370, 530, 72, 30);

        jLabel11.setFont(new java.awt.Font("Century751 No2 BT", 1, 18)); // NOI18N
        jLabel11.setText("Total : ");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(369, 467, 64, 23);

        Total.setEditable(false);
        jPanel1.add(Total);
        Total.setBounds(369, 496, 156, 30);

        jLabel12.setFont(new java.awt.Font("Century751 No2 BT", 1, 18)); // NOI18N
        jLabel12.setText("Bayar :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(616, 467, 78, 23);

        jLabel13.setFont(new java.awt.Font("Century751 SeBd BT", 0, 14)); // NOI18N
        jLabel13.setText("Cash :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(610, 500, 64, 18);

        Cash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CashActionPerformed(evt);
            }
        });
        Cash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CashKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CashKeyTyped(evt);
            }
        });
        jPanel1.add(Cash);
        Cash.setBounds(686, 496, 131, 30);

        jLabel14.setFont(new java.awt.Font("Century751 SeBd BT", 0, 14)); // NOI18N
        jLabel14.setText("Susok :");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(610, 540, 64, 18);

        JSusok.setEditable(false);
        jPanel1.add(JSusok);
        JSusok.setBounds(686, 531, 131, 30);

        Reset.setBackground(new java.awt.Color(0, 51, 153));
        Reset.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        Reset.setForeground(new java.awt.Color(255, 255, 255));
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        jPanel1.add(Reset);
        Reset.setBounds(150, 620, 100, 30);

        Exit.setBackground(new java.awt.Color(204, 0, 0));
        Exit.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel1.add(Exit);
        Exit.setBounds(280, 620, 100, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 913, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AngkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AngkaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AngkaActionPerformed

    private void CashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CashActionPerformed

    private void TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahActionPerformed
        // TODO add your handling code here:
        jumlah++;
        Angka.setText(String.valueOf(jumlah));
    }//GEN-LAST:event_TambahActionPerformed

    private void TambahInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_TambahInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_TambahInputMethodTextChanged

    private void kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangActionPerformed
        // TODO add your handling code here:
        jumlah--;
        if (jumlah <= 0){
            JOptionPane.showMessageDialog(this, "Yakali jumlah minus", "hayoo hayoo", JOptionPane.WARNING_MESSAGE);
            jumlah = 1;
        }else {
             Angka.setText(String.valueOf(jumlah));
        }
    }//GEN-LAST:event_kurangActionPerformed

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        // TODO add your handling code here:
        String tampil;
        tampil = "";
        int total = 0;
        int totalharga = 0;
        int diskon = 0;
        int total1 = 0;
        
        if(Rb1.isSelected()){
           total1 = jumlah * 50000;
        }else if(Rb2.isSelected()){
           total1 = jumlah * 150000;
        }else if(Rb3.isSelected()){
           total1 = jumlah * 200000;
        }else if(Rb4.isSelected()){
           total1 = jumlah * 250000;
        }else if(Rb5.isSelected()){
           total1 = jumlah * 300000;
        }else if(Rb6.isSelected()){
           total1 = jumlah * 350000;
        }else if(Rb7.isSelected()){
           total1 = jumlah * 400000;
        }else if(Rb8.isSelected()){
           total1 = jumlah * 450000;
        }else if(Rb9.isSelected()){
           total1 = jumlah * 500000;
        }else{
            JOptionPane.showMessageDialog(this, "isi menu bangggg", "hayooo", JOptionPane.WARNING_MESSAGE,icon);
            return;
        }
        
        if(Rbt1.isSelected()){
            total += 50000 * jumlah;
        }else if(Rbt2.isSelected()){
            total += 40000 * jumlah;
        }else if(Rbt3.isSelected()){
            total += 60000 * jumlah;
        }else if(Rbt4.isSelected()){
            total += 80000 * jumlah;
        }else if(Rbt5.isSelected()){
            total += 35000 * jumlah;
        }else if(Rbt6.isSelected()){
            total += 200000 * jumlah;
        }
        totalharga = total1 + total;
        if (total1 == 0){
            Total.setText("");
        }else if(totalharga > 100000){
            diskon = totalharga * 5/100;
            tampil += totalharga - diskon;
            Total.setText("Rp. "+tampil);
        }else if(totalharga <= 100000){
            tampil += totalharga ;
            Total.setText("Rp. "+tampil);
        }else{
            Total.setText("");
        }
        
        
        if(jumlah == 0){
            JOptionPane.showMessageDialog(this, "jumlah nya bang isii", "buhh", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_HitungActionPerformed

    private void CashKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CashKeyReleased
        // TODO add your handling code here:
        try{
            int totalHarga = Integer.parseInt(Total.getText().replace("Rp. ", ""));
            int cash = Integer.parseInt(Cash.getText());
            int kembalian = cash - totalHarga;
            if (cash < totalHarga) {
                JSusok.setText("Uang anda kurang");
            } else {
                JSusok.setText("Rp. " +kembalian);
            }
        }catch (NumberFormatException e) {
            JSusok.setText("Masukkan angka");
        }
    }//GEN-LAST:event_CashKeyReleased

    private void CashKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CashKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

//    buat kondisi inputan angka saja
        if (!Character.isDigit(c)) {
            evt.consume();  // Jika bukan angka,(tidak izinkan input)
    }
        
    }//GEN-LAST:event_CashKeyTyped

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        Menu.clearSelection();
        Topping.clearSelection();
        Angka.setText(String.valueOf(jumlah = 0));
        Total.setText("");
        Cash.setText("");
        JSusok.setText("Rp." );
    }//GEN-LAST:event_ResetActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        int exit = JOptionPane.showConfirmDialog(null,"Akhiri Pesanan?","Keluar",JOptionPane.YES_NO_OPTION);
        if (exit == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Angka;
    private javax.swing.JTextField Cash;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Hitung;
    private javax.swing.JTextField JSusok;
    private javax.swing.ButtonGroup Menu;
    private javax.swing.JRadioButton Rb1;
    private javax.swing.JRadioButton Rb2;
    private javax.swing.JRadioButton Rb3;
    private javax.swing.JRadioButton Rb4;
    private javax.swing.JRadioButton Rb5;
    private javax.swing.JRadioButton Rb6;
    private javax.swing.JRadioButton Rb7;
    private javax.swing.JRadioButton Rb8;
    private javax.swing.JRadioButton Rb9;
    private javax.swing.JRadioButton Rbt1;
    private javax.swing.JRadioButton Rbt2;
    private javax.swing.JRadioButton Rbt3;
    private javax.swing.JRadioButton Rbt4;
    private javax.swing.JRadioButton Rbt5;
    private javax.swing.JRadioButton Rbt6;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Tambah;
    private javax.swing.ButtonGroup Topping;
    private javax.swing.JTextField Total;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton kurang;
    // End of variables declaration//GEN-END:variables
}
