/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modulsatu;
/**
 *
 * @author THINKPAD
 */
public class formBimbel2 extends javax.swing.JFrame {


/**
     * Creates new form formBimbel
     */
    public formBimbel2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupGender = new javax.swing.ButtonGroup();
        groupTime = new javax.swing.ButtonGroup();
        groupKursus = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Tanggal_Lahir = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Sekolah = new javax.swing.JTextField();
        Alamat = new javax.swing.JTextField();
        Telepon = new javax.swing.JTextField();
        Ortu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Kelas = new javax.swing.JTextField();
        kelamin = new javax.swing.JTextField();
        Kursus = new javax.swing.JTextField();
        hari = new javax.swing.JTextField();
        Waktu = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(231, 143, 129));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 207, 179));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nama Lengkap");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, -1, -1));

        Nama.setEditable(false);
        Nama.setBackground(new java.awt.Color(255, 244, 234));
        Nama.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });
        jPanel2.add(Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 6, 373, -1));

        jLabel2.setText("Tanggal Lahir");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 55, -1, -1));

        jLabel3.setText("Asal Sekolah");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 93, -1, -1));

        jLabel6.setText("Alamat");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 133, -1, -1));

        jLabel7.setText("No. Telepon");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 181, -1, -1));

        jLabel8.setText("Nama Orang Tua");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 230, -1, -1));

        jLabel10.setText("Program Kursus");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 270, -1, -1));

        Tanggal_Lahir.setEditable(false);
        Tanggal_Lahir.setBackground(new java.awt.Color(255, 244, 234));
        jPanel2.add(Tanggal_Lahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 52, 155, -1));

        jLabel11.setText("Hari Kursus");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 310, -1, -1));

        jLabel12.setText("Waktu Kursus");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 350, -1, -1));

        Sekolah.setEditable(false);
        Sekolah.setBackground(new java.awt.Color(255, 244, 234));
        jPanel2.add(Sekolah, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 90, 155, -1));

        Alamat.setEditable(false);
        Alamat.setBackground(new java.awt.Color(255, 244, 234));
        jPanel2.add(Alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 130, 373, -1));

        Telepon.setEditable(false);
        Telepon.setBackground(new java.awt.Color(255, 244, 234));
        jPanel2.add(Telepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 178, 373, -1));

        Ortu.setEditable(false);
        Ortu.setBackground(new java.awt.Color(255, 244, 234));
        jPanel2.add(Ortu, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 227, 373, -1));

        jLabel4.setText("Jenis Kelamin");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 50, -1, -1));

        jLabel5.setText("Kelas");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 93, -1, -1));

        Kelas.setEditable(false);
        Kelas.setBackground(new java.awt.Color(255, 244, 234));
        jPanel2.add(Kelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 90, 105, -1));

        kelamin.setEditable(false);
        kelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelaminActionPerformed(evt);
            }
        });
        jPanel2.add(kelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 47, 105, -1));

        Kursus.setEditable(false);
        jPanel2.add(Kursus, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 267, 373, -1));

        hari.setEditable(false);
        jPanel2.add(hari, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 307, 373, -1));

        Waktu.setEditable(false);
        jPanel2.add(Waktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 347, 373, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 120, 540, 400));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\THINKPAD\\Downloads\\bebo_2673697 (1).png")); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel14.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Kursus Belajar");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 12, -1, -1));

        jLabel15.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Beeboo");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 37, -1, -1));

        jLabel16.setFont(new java.awt.Font("Exotc350 DmBd BT", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Formulir");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 37, -1, 31));

        jLabel17.setFont(new java.awt.Font("Exotc350 DmBd BT", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Pendaftaran");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 37, -1, 31));

        jLabel18.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Jl. Duta Daan 117, Banjar, Jawa Timur 47433");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 74, -1, -1));

        jLabel19.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Telp : 0123458939 | E-mail: kursus_Beebo@gmail.com");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        btnKeluar.setBackground(new java.awt.Color(142, 172, 205));
        btnKeluar.setForeground(new java.awt.Color(255, 255, 255));
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        jPanel1.add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 530, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 570, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
//          
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void kelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelaminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formBimbel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formBimbel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formBimbel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formBimbel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formBimbel2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Alamat;
    public javax.swing.JTextField Kelas;
    public javax.swing.JTextField Kursus;
    public javax.swing.JTextField Nama;
    public javax.swing.JTextField Ortu;
    public javax.swing.JTextField Sekolah;
    public javax.swing.JTextField Tanggal_Lahir;
    public javax.swing.JTextField Telepon;
    public javax.swing.JTextField Waktu;
    private javax.swing.JButton btnKeluar;
    private javax.swing.ButtonGroup groupGender;
    private javax.swing.ButtonGroup groupKursus;
    private javax.swing.ButtonGroup groupTime;
    public javax.swing.JTextField hari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField kelamin;
    // End of variables declaration//GEN-END:variables
}
