/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author shahaflanjaya
 */
public class Hasil extends javax.swing.JFrame {

    /**
     * Creates new form Hasil
     */
    public Hasil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelNama = new javax.swing.JLabel();
        jTextFieldNama = new javax.swing.JTextField();
        jLabelTempat = new javax.swing.JLabel();
        jTextFieldTempat = new javax.swing.JTextField();
        jLabelTggl = new javax.swing.JLabel();
        jTextFieldTggl = new javax.swing.JTextField();
        jLabelAlamat = new javax.swing.JLabel();
        jLabelNo = new javax.swing.JLabel();
        jLabelJenis = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelProdi = new javax.swing.JLabel();
        jLabelFakultas = new javax.swing.JLabel();
        jTextFieldAlamat = new javax.swing.JTextField();
        jTextFieldNo = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldProdi = new javax.swing.JTextField();
        jTextFieldFakultas = new javax.swing.JTextField();
        jTextFieldjenis = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Folder Baru/hardcore.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 580, 180));

        jLabelNama.setFont(new java.awt.Font("Geometr212 BkCn BT", 1, 12)); // NOI18N
        jLabelNama.setText("Nama              ");
        jPanel1.add(jLabelNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jTextFieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNamaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 275, -1));

        jLabelTempat.setFont(new java.awt.Font("Geometr212 BkCn BT", 1, 12)); // NOI18N
        jLabelTempat.setText("Tempat lahir    ");
        jPanel1.add(jLabelTempat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 95, -1));

        jTextFieldTempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTempatActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldTempat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 275, -1));

        jLabelTggl.setFont(new java.awt.Font("Geometr212 BkCn BT", 1, 12)); // NOI18N
        jLabelTggl.setText("Tggl Lahir");
        jPanel1.add(jLabelTggl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));
        jPanel1.add(jTextFieldTggl, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 239, 275, -1));

        jLabelAlamat.setFont(new java.awt.Font("Geometr212 BkCn BT", 1, 12)); // NOI18N
        jLabelAlamat.setText("Alamat        ");
        jPanel1.add(jLabelAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        jLabelNo.setFont(new java.awt.Font("Geometr212 BkCn BT", 1, 12)); // NOI18N
        jLabelNo.setText("No.Tlp        ");
        jPanel1.add(jLabelNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jLabelJenis.setFont(new java.awt.Font("Geometr212 BkCn BT", 1, 12)); // NOI18N
        jLabelJenis.setText("Jenis Kelamin");
        jPanel1.add(jLabelJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        jLabelEmail.setFont(new java.awt.Font("Geometr212 BkCn BT", 1, 12)); // NOI18N
        jLabelEmail.setText("Email     ");
        jPanel1.add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        jLabelProdi.setFont(new java.awt.Font("Geometr212 BkCn BT", 1, 12)); // NOI18N
        jLabelProdi.setText("Prodi");
        jPanel1.add(jLabelProdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        jLabelFakultas.setFont(new java.awt.Font("Geometr212 BkCn BT", 1, 12)); // NOI18N
        jLabelFakultas.setText("Fakultas        ");
        jPanel1.add(jLabelFakultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        jTextFieldAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAlamatActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 275, -1));

        jTextFieldNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 275, -1));
        jPanel1.add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 275, -1));
        jPanel1.add(jTextFieldProdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 434, 275, -1));
        jPanel1.add(jTextFieldFakultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 270, -1));
        jPanel1.add(jTextFieldjenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 270, -1));

        jButton1.setText("Keluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFieldNamaActionPerformed

    private void jTextFieldTempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTempatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTempatActionPerformed

    private void jTextFieldNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNoActionPerformed

    private void jTextFieldAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAlamatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hasil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAlamat;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFakultas;
    private javax.swing.JLabel jLabelJenis;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JLabel jLabelNo;
    private javax.swing.JLabel jLabelProdi;
    private javax.swing.JLabel jLabelTempat;
    private javax.swing.JLabel jLabelTggl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField jTextFieldAlamat;
    public javax.swing.JTextField jTextFieldEmail;
    public javax.swing.JTextField jTextFieldFakultas;
    public javax.swing.JTextField jTextFieldNama;
    public javax.swing.JTextField jTextFieldNo;
    public javax.swing.JTextField jTextFieldProdi;
    public javax.swing.JTextField jTextFieldTempat;
    public javax.swing.JTextField jTextFieldTggl;
    public javax.swing.JTextField jTextFieldjenis;
    // End of variables declaration//GEN-END:variables
}
