/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package m1pemvis;
import javax.swing.JOptionPane;
/**
 *
 * @author giska
 */
public class Formulir extends javax.swing.JFrame {

    /**
     * Creates new form Formulir
     */
    public Formulir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        Tempat = new javax.swing.JLabel();
        Tanggal = new javax.swing.JLabel();
        Gender = new javax.swing.JLabel();
        Alamat = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Prodi = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Universitas = new javax.swing.JLabel();
        Keluar = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        Simpan = new javax.swing.JButton();
        prodi = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        tempat = new javax.swing.JTextField();
        tanggal = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        Wanita = new javax.swing.JRadioButton();
        Pria = new javax.swing.JRadioButton();
        universitas = new javax.swing.JComboBox<>();
        Data = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setText("FORMULIR PENDAFTARAN DESIGN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel2.setText("KABUPATEN BANGKALAN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jLabel3.setText("JL. Mayjend Sungkono Bangkalan Madura");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        Nama.setText("Nama :");
        jPanel1.add(Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        Tempat.setText("Tempat Lahir :");
        jPanel1.add(Tempat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        Tanggal.setText("Tanggal Lahir :");
        jPanel1.add(Tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        Gender.setText("Jenis Kelamin :");
        jPanel1.add(Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        Alamat.setText("Alamat :");
        jPanel1.add(Alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        Email.setText("Email :");
        jPanel1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        Prodi.setText("Prodi :");
        jPanel1.add(Prodi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        Universitas.setText("Universitas :");
        jPanel1.add(Universitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, -1));

        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });
        jPanel1.add(Keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, -1, -1));

        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        jPanel1.add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 590, -1, -1));

        Simpan.setText("Simpan");
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });
        jPanel1.add(Simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 590, -1, -1));

        prodi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodiActionPerformed(evt);
            }
        });
        jPanel1.add(prodi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 280, 30));

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        jPanel1.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 280, 30));

        tempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempatActionPerformed(evt);
            }
        });
        jPanel1.add(tempat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 280, 30));

        tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalActionPerformed(evt);
            }
        });
        jPanel1.add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 280, 30));

        alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatActionPerformed(evt);
            }
        });
        jPanel1.add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 280, 30));

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 280, 30));

        buttonGroup1.add(Wanita);
        Wanita.setText("Wanita");
        jPanel1.add(Wanita, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        buttonGroup1.add(Pria);
        Pria.setText("Pria");
        Pria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriaActionPerformed(evt);
            }
        });
        jPanel1.add(Pria, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        universitas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UI", "UGM", "UNAIR", "UNESA", "UPN", "UTM", "BINUS", "UMM", "UNDIP", " ", " " }));
        universitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                universitasActionPerformed(evt);
            }
        });
        jPanel1.add(universitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 280, 30));

        Data.setText("Data sudah lengkap");
        Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataActionPerformed(evt);
            }
        });
        jPanel1.add(Data, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed

    int response = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

    if (response == JOptionPane.YES_OPTION) {
        System.exit(0);
    }
    }//GEN-LAST:event_KeluarActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        nama.setText("");  
        tempat.setText("");  
        tanggal.setText("");  
        alamat.setText("");  
        email.setText("");  
        prodi.setText("");  
        universitas.setSelectedIndex(0);  
        buttonGroup1.clearSelection();
        Data.setSelected(false);
    }//GEN-LAST:event_ResetActionPerformed

    private void prodiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodiActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void tempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempatActionPerformed

    private void tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalActionPerformed

    private void alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void universitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_universitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_universitasActionPerformed

    private void PriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriaActionPerformed

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
    hasil w = new hasil ();
    w.Nama.setText(nama.getText());
    w.Tempat.setText(tempat.getText());
    w.Tanggal.setText (tanggal.getText());
    w.Gender.setText (Gender.getText());
    w.Alamat.setText (alamat.getText());
    w.Email.setText (email.getText());
    w.Prodi.setText (prodi.getText());
    w.Universitas.setText (universitas.getSelectedItem().toString());
    w.setVisible(true);
    
    this.dispose();
        
    String namaInput = nama.getText();
    String tempatInput = tempat.getText();
    String tanggalInput = tanggal.getText();
    String alamatInput = alamat.getText();
    String emailInput = email.getText();
    String prodiInput = prodi.getText();
    String universitasInput = (String) universitas.getSelectedItem();

    
    String kelaminInput = "";
    if (Pria.isSelected()) {
        kelaminInput = "Pria";
    } else if (Wanita.isSelected()) {
        kelaminInput = "Wanita";
    }


    if (!Wanita.isSelected()) {
        JOptionPane.showMessageDialog(this, 
            "Harap centang checkbox untuk melanjutkan.", 
            "Peringatan", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }

 
    //String message = "Data yang disimpan:\n" +
                //     "Nama: " + namaInput + "\n" +
              //       "Tempat: " + tempatInput + "\n" +
            //         "Tanggal: " + tanggalInput + "\n" +
          //           "Kelamin: " + kelaminInput + "\n" +
        //             "Alamat: " + alamatInput + "\n" +
      //               "Email: " + emailInput + "\n" +
    //                 "Prodi: " + prodiInput + "\n" +
  //                   "Universitas: " + universitasInput;
//
    //JOptionPane.showMessageDialog(this, message, "Data Tersimpan", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_SimpanActionPerformed

    private void DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataActionPerformed
                                  
       if (!Data.isSelected()) {
        Data.setText("Tidak dapat disimpan, harap centang terlebih dahulu!!");
        return;
    } 
    }//GEN-LAST:event_DataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alamat;
    private javax.swing.JCheckBox Data;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Gender;
    private javax.swing.JButton Keluar;
    private javax.swing.JLabel Nama;
    public javax.swing.JRadioButton Pria;
    private javax.swing.JLabel Prodi;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Simpan;
    private javax.swing.JLabel Tanggal;
    private javax.swing.JLabel Tempat;
    private javax.swing.JLabel Universitas;
    public javax.swing.JRadioButton Wanita;
    public javax.swing.JTextField alamat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    public javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField nama;
    public javax.swing.JTextField prodi;
    public javax.swing.JTextField tanggal;
    public javax.swing.JTextField tempat;
    public javax.swing.JComboBox<String> universitas;
    // End of variables declaration//GEN-END:variables
}
