/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pemvisa;

import javax.swing.JOptionPane;

/**
 *
 * @author Shely
 */
public class cobaAja extends javax.swing.JFrame {

    /**
     * Creates new form cobaAja
     */
    public cobaAja() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        labelGambar = new javax.swing.JLabel();
        labelnamaformulir = new javax.swing.JLabel();
        labelSekolah = new javax.swing.JLabel();
        labelJalan = new javax.swing.JLabel();
        labelnomer = new javax.swing.JLabel();
        labelNpsn = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        labelNisn = new javax.swing.JLabel();
        labelAlamat = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelKelamin = new javax.swing.JLabel();
        labelTelepon = new javax.swing.JLabel();
        labelKelas = new javax.swing.JLabel();
        checkboxData = new javax.swing.JCheckBox();
        textFieldNama = new javax.swing.JTextField();
        textFieldNisn = new javax.swing.JTextField();
        textFieldAlamat = new javax.swing.JTextField();
        textFieldEmail = new javax.swing.JTextField();
        buttonLaki = new javax.swing.JRadioButton();
        buttonPerempuan = new javax.swing.JRadioButton();
        labelTempat = new javax.swing.JLabel();
        labelTanggal = new javax.swing.JLabel();
        textFieldtempat = new javax.swing.JTextField();
        textFieldTanggal = new javax.swing.JTextField();
        textFieldTelpon = new javax.swing.JTextField();
        comboBoxkelas = new javax.swing.JComboBox<>();
        buttonBatal = new javax.swing.JButton();
        buttonReset = new javax.swing.JButton();
        buttonSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        labelGambar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shely\\Downloads\\foto.jpg")); // NOI18N

        labelnamaformulir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelnamaformulir.setText("FORMULIR PENDAFTARAN SISWA SEKOLAH");

        labelSekolah.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelSekolah.setText("SMA NEGERI 1 NUSANTARA");

        labelJalan.setText("JL. Raya Telang, PO, Box. 2 Kamal, Bangkalan - Madura");

        labelnomer.setText("Telp : (031) 3011146, Fax (031) 3011506");

        labelNpsn.setText("NPSN : 20506325");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(labelGambar)
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelnamaformulir, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(labelSekolah))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(labelJalan)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelnomer, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelNpsn)
                .addGap(205, 205, 205))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(labelGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(labelnamaformulir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelSekolah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelJalan)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelnomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNpsn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelNama.setText("Nama : ");

        labelNisn.setText("NISN : ");

        labelAlamat.setText("Alamat : ");

        labelEmail.setText("Email :");

        labelKelamin.setText("Jenis Kelamin :");

        labelTelepon.setText("No. Telepon : ");

        labelKelas.setText("Kelas :");

        checkboxData.setText("Data Yang Saya Masukkan Sudah Benar.");
        checkboxData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxDataActionPerformed(evt);
            }
        });

        textFieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNamaActionPerformed(evt);
            }
        });

        textFieldNisn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNisnActionPerformed(evt);
            }
        });

        textFieldAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldAlamatActionPerformed(evt);
            }
        });

        textFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldEmailActionPerformed(evt);
            }
        });

        buttonGroup1.add(buttonLaki);
        buttonLaki.setText("Laki-Laki");
        buttonLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLakiActionPerformed(evt);
            }
        });

        buttonGroup1.add(buttonPerempuan);
        buttonPerempuan.setText("Perempuan");

        labelTempat.setText("Tempat Lahir : ");

        labelTanggal.setText("Tanggal Lahir : ");

        textFieldtempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldtempatActionPerformed(evt);
            }
        });

        textFieldTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldTanggalActionPerformed(evt);
            }
        });

        textFieldTelpon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldTelponActionPerformed(evt);
            }
        });

        comboBoxkelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Pilihan Kelas ---", "1. Akselirasi", "2. Unggulan", "3. Reguler" }));
        comboBoxkelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxkelasActionPerformed(evt);
            }
        });

        buttonBatal.setText("Batal");
        buttonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBatalActionPerformed(evt);
            }
        });

        buttonReset.setText("Reset");
        buttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetActionPerformed(evt);
            }
        });

        buttonSimpan.setText("Simpan");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTelepon)
                            .addComponent(labelAlamat)
                            .addComponent(labelEmail)
                            .addComponent(labelKelamin)
                            .addComponent(labelKelas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldTelpon, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textFieldNisn, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textFieldtempat, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textFieldTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textFieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(57, 57, 57))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(buttonLaki)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(buttonPerempuan)
                                    .addGap(98, 98, 98)))
                            .addComponent(comboBoxkelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNama)
                            .addComponent(labelNisn)
                            .addComponent(labelTempat)
                            .addComponent(labelTanggal))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(checkboxData)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonBatal)
                        .addGap(130, 130, 130)
                        .addComponent(buttonReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonSimpan)
                        .addGap(18, 18, 18))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNama))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(labelNisn, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(textFieldNisn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldtempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTempat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTanggal))
                        .addGap(18, 18, 18)
                        .addComponent(labelAlamat))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(textFieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKelamin)
                    .addComponent(buttonLaki)
                    .addComponent(buttonPerempuan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelepon)
                    .addComponent(textFieldTelpon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKelas)
                    .addComponent(comboBoxkelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(checkboxData)
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBatal)
                    .addComponent(buttonReset)
                    .addComponent(buttonSimpan))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkboxDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxDataActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_checkboxDataActionPerformed

    private void textFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNamaActionPerformed

    private void textFieldAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldAlamatActionPerformed

    private void textFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldEmailActionPerformed

    private void buttonLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLakiActionPerformed

    private void textFieldNisnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNisnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNisnActionPerformed

    private void textFieldtempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldtempatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldtempatActionPerformed

    private void textFieldTelponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldTelponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldTelponActionPerformed

    private void textFieldTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldTanggalActionPerformed

    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
        // TODO add your handling code here:
//        bersihkan field teks
        textFieldNama.setText(null);
        textFieldtempat.setText(null);
        textFieldTanggal.setText(null);
        textFieldAlamat.setText(null); 
       textFieldNisn.setText(null);
        textFieldEmail.setText(null);
        textFieldTelpon.setText(null);
//        bersihkan pilihan dari grup tombol
        buttonGroup1.clearSelection();
//        bersihkan checkbox
        checkboxData.setSelected(false);
//        atur combo box kelas ke nilai default

        comboBoxkelas.setSelectedIndex(0);
    }//GEN-LAST:event_buttonResetActionPerformed

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        // TODO add your handling code here:
//        ambil data dari form
        String nama=textFieldNama.getText();
        String nisn = textFieldNisn.getText();
        String tempatLahir = textFieldtempat.getText();
        String tanggallahir = textFieldTanggal.getText();
        String alamat = textFieldAlamat.getText();
        String email = textFieldEmail.getText();
        String telepon = textFieldTelpon.getText();
        String gender = buttonLaki.isSelected()? "Laki-Laki" :
                buttonPerempuan.isSelected()? "Perempuan" : "";
        String kelas = comboBoxkelas.getSelectedItem().toString();
//        cek apakah checkbox dicentang
        if (!checkboxData.isSelected()){
            JOptionPane.showMessageDialog(this, "Harap centang checkbox untuk melanjutkan.", "Peringatan", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
//        ngatur combo box biar kosong
        comboBoxkelas.addItem("");
        comboBoxkelas.setSelectedIndex(4);
//        cek data harus diisi dahulu
        if (textFieldNama.getText().isEmpty() || textFieldAlamat.getText().isEmpty() || textFieldEmail.getText().isEmpty() || textFieldNisn.getText().isEmpty() || textFieldTanggal.getText().isEmpty() || textFieldTelpon.getText().isEmpty() || textFieldtempat.getText().isEmpty() || buttonLaki.getText().isEmpty() || buttonPerempuan.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Harap diisi terlebih dahulu!!", "Peringatan", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
//        buat instance dari frame kedua dan kirim data
        Frame2 frame2 = new Frame2();
        frame2.setData(nama, nisn, tempatLahir, tanggallahir, alamat, email, telepon, gender, kelas);
        frame2.setVisible(true);
//        frame2.setVisible(false);
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void comboBoxkelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxkelasActionPerformed
        // TODO add your handling code here:
//        comboBoxkelas.removeItem("---Pilihan Kelas ---");
        
    }//GEN-LAST:event_comboBoxkelasActionPerformed

    private void buttonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBatalActionPerformed
        // TODO add your handling code here:
//        this.setVisible(false);
        dispose(); //menutup jendela sepenuhnya
    }//GEN-LAST:event_buttonBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cobaAja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cobaAja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cobaAja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cobaAja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cobaAja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBatal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton buttonLaki;
    private javax.swing.JRadioButton buttonPerempuan;
    private javax.swing.JButton buttonReset;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JCheckBox checkboxData;
    private javax.swing.JComboBox<String> comboBoxkelas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelAlamat;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelGambar;
    private javax.swing.JLabel labelJalan;
    private javax.swing.JLabel labelKelamin;
    private javax.swing.JLabel labelKelas;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelNisn;
    private javax.swing.JLabel labelNpsn;
    private javax.swing.JLabel labelSekolah;
    private javax.swing.JLabel labelTanggal;
    private javax.swing.JLabel labelTelepon;
    private javax.swing.JLabel labelTempat;
    private javax.swing.JLabel labelnamaformulir;
    private javax.swing.JLabel labelnomer;
    private javax.swing.JTextField textFieldAlamat;
    private javax.swing.JTextField textFieldEmail;
    private javax.swing.JTextField textFieldNama;
    private javax.swing.JTextField textFieldNisn;
    private javax.swing.JTextField textFieldTanggal;
    private javax.swing.JTextField textFieldTelpon;
    private javax.swing.JTextField textFieldtempat;
    // End of variables declaration//GEN-END:variables
}
